### ISSUE TITLE
Upgrade aws-sdk-go-v2 to latest

### ISSUE THREAD

**Issue by noda-sin** [yugabyte/yb-voyager#1340]
Jira Link: [DB-13469](https://yugabyte.atlassian.net/browse/DB-13469)
I'd like to use voyager to migrate data from in-house object storage that be compatible with S3.
To support in-house object storage, I need to change s3 endpoint url.
Recently, aws-sdk-go-v2 support a feature to change endpoint url from outside config, environments, like `AWS_ENDPOINT_URL`.

https://github.com/aws/aws-sdk-go-v2/pull/2328

So, I'd like to bump up aws-sdk-sdk-v2 version that used in voyager.

**Comment by hbhanawat** [comment]
Older issue. SHould not be relevant anymore. Please reopen if seen again.

**Comment by shubham-yb** [comment]
AWS SDK version will have to be updated.

**Comment by noda-sin** [comment]
@shubham-yb 

Thank you for understanding.
Just notes. I tried to upgrade to `v1.25.0` in my local when I created this ticket, then `AWS_ENDPOINT_URL` env worked.
