### ISSUE TITLE
[MySQL] Handle duplicate index names

### ISSUE THREAD

**Issue by amit-yb** [yugabyte/yb-voyager#136]
MySQL allows more than one indexes to have same name in the same database.
```
mysql> CREATE TABLE t1 (k integer, v integer);
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE t2 (k integer, v integer);
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE INDEX idx on t1 (v);
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> CREATE INDEX idx on t2 (v);
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> SELECT DISTINCT TABLE_NAME, INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = 'test';
+------------+------------+
| TABLE_NAME | INDEX_NAME |
+------------+------------+
| t1         | idx        |
| t2         | idx        |
+------------+------------+
2 rows in set (0.00 sec)
```
Migrating such a database will fail in the `import data` command (after data is imported and indexes are being created). e.g.
```
All the tables are imported
setting resume value for sequences           done
creating indexes           
    ERROR: relation "idx_fk_film_id" already exists (SQLSTATE 42P07)
    STATEMENT: CREATE INDEX idx_fk_film_id ON inventory (film_id);
```
https://downloads.mysql.com/docs/sakila-db.zip schema can be used to reproduce the issue.

Postgres and Oracle does not allow duplicate index names.

To handle such situations, `ora2pg` does provide an `INDEX_RENAMING` option (https://ora2pg.darold.net/documentation.html#:~:text=but%20can%20help.-,INDEXES_RENAMING,-Enable%20this%20directive).

yb_migrate should enable the `INDEX_RENAMING` option (based on user input).

Until the issue is fixed, users can edit the `<export-dir>/schema/tables/INDEXES_table.sql` file to rename the duplicate indexes and retry the `import data` command. The `import data` will straight-away proceed to creation of indexes.

**Comment by pc-beast** [comment]
Is this issue open to working on by external contributors? 

how is it being planned to be implemented? Is the user supposed to get a prompt in shell asking him to rename the index or is there some other way?
