### ISSUE TITLE
Allow option to specific CREATE INDEX to be CONCURRENTLY or NONCONCURRENTLY for target database YugabyteDB

### ISSUE THREAD

**Issue by ssherwood** [yugabyte/yb-voyager#1382]
Jira Link: [DB-13446](https://yugabyte.atlassian.net/browse/DB-13446)
YugabyteDB defaults index creation to [CONCURRENTLY](https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_index/#concurrently).  This is most appropriate for on-line (live) migrations.  However, for offline migrations, it may be desirable to have YugabyteDB use NONCONCURRENTLY instead.

This should be an optional configuration option when generating the CREATE INDEX output for YugabyteDB.

**Comment by hbhanawat** [comment]
@makalaaneesh is this issue still relevant?

**Comment by makalaaneesh** [comment]
With [voyager 1.7.2](https://docs.yugabyte.com/preview/yugabyte-voyager/release-notes/#v1-7-2-july-4-2024), we changed the workflows to import indexes in the `import schema` step as opposed to `import-schema --post-snapshot-import true` step. 

With this change, the indexes will be created at at time when there is no data present in the tables. Therefore, having the ability to create indexes NON-CONCURRENTLY is not relevant anymore.
