### ISSUE TITLE
Code Refactoring: New Type for ExportDir

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#175]
Jira Link: [DB-13525](https://yugabyte.atlassian.net/browse/DB-13525)
create a type called as ExportDir
instantiate an object of ExportDir with the exportDir provided by the user.
and then use the methods of the ExportDir object to directly get the paths, for example,
-- exportDir.SchemaDir()
-- exportDir.ReportFilePath()
-- exportDir.TablesFilePath()

Thanks to @amit-yb for this suggestion.

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant. reopen in case it needs a fix.
