### ISSUE TITLE
[Voyager] [Assess Migration] Unique constraint error in case queryid is empty / duplicate in pg_stat_statements

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#1791]
Jira Link: [DB-13651](https://yugabyte.atlassian.net/browse/DB-13651)
### Description

In case we have a few rows in the PG SS which are not accessible to the migration user, their query and queryid come up as empty. This causes a Unique constraint error during the insertion of data in the meta db.
We need to handle this case. 
Even for privileged users, the query id can be same for multiple rows and thus this check will fail.

```
       queryid       |                             query                             | calls 
---------------------+---------------------------------------------------------------+-------
 -778708154092909096 | select query from pg_stat_statements where queryid=$1         |     1
 -778708154092909096 | select query from pg_stat_statements where queryid=$1         |     3
 5787495921082967521 | select queryid from pg_stat_statements order by queryid       |     5
 5787495921082967521 | select queryid from pg_stat_statements order by queryid       |     4
 6856587723325601129 | select * from pg_stat_statements                              |     2
 6856587723325601129 | select * from pg_stat_statements                              |     1
 9029586359568942362 | select queryid,query from pg_stat_statements order by queryid |     2
 9029586359568942362 | select queryid,query from pg_stat_statements order by queryid |     2
(8 rows)
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by sanyamsinghal** [comment]
Also need to explore -
1. What were the missing permissions on user in this case
2. does the voyager assess-migration user(source) as per the docs, does have enough permissions to read the all the required queries from `pgss`

**Comment by sanyamsinghal** [comment]
Fixed in https://github.com/yugabyte/yb-voyager/pull/1792 and https://github.com/yugabyte/yb-voyager/pull/1800
