### ISSUE TITLE
[Voyager] Add missing unsupported functions to the Unsupported Query Constructs list

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#1795]
Jira Link: [DB-13671](https://yugabyte.atlassian.net/browse/DB-13671)
### Description

There a few functions which we are not reporting in the Unsupported Query Constructs list in the Assessment Report.

XML functions: xml_is_well_formed_document, xml_is_well_formed support

Full list to be picked from:
https://www.postgresql.org/docs/16/functions-xml.html

Advisory Lock functions: pg_advisory_lock_shared, pg_advisory_unlock_shared, pg_advisory_xact_lock_shared 

Full list to be picked from: https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by sanyamsinghal** [comment]
fixed in https://github.com/yugabyte/yb-voyager/pull/1798
