### ISSUE TITLE
[Voyager] Migration assessment created, but not shown in UI hosted by yugabyted

### ISSUE THREAD

**Issue by jlisthood** [yugabyte/yb-voyager#1865]
Jira Link: [DB-13970](https://yugabyte.atlassian.net/browse/DB-13970)
### Description

**Note:**
I am unsure if the root issue is in Voyager or in Yugabyted, but since Voyager is the tool used for migration assessments, I am filing here.

**Context**:
- YB-Voyager Version: GIT_COMMIT_HASH=4f3afcd389cac1236f0051c38215ae360420fb3e, VERSION=1.8.5-rc1
- YB Version: 2024.1.3.0

**Issue**:
When following the guide [here](https://docs.yugabyte.com/preview/yugabyte-voyager/migrate/assess-migration/) to do a migration assessment, the actual assessment completes fine but I cannot access it in the UI
```
GIT_COMMIT_HASH=4f3afcd389cac1236f0051c38215ae360420fb3e
migrationID: a7ea497a-7c6c-4312-a7c5-1298a19df727
gathering metadata and stats from 'postgresql' source database...
sleep interval for calculating iops: 120 seconds
Assessment metadata collection started for ''public'' schemas
Collecting db queries summary...
Collecting index to table mapping...
Collecting object_type_mapping...
Collecting table columns count...
Collecting table columns data types...
Collecting table index iops...
Collecting table index sizes...
Collecting table row counts...
Collecting schema information...
Assessment metadata collection completed
gathered assessment metadata files at '/home/ec2-user/migration/assessment/metadata'
Generating assessment report...
generated JSON assessment report at: /home/ec2-user/migration/assessment/reports/migration_assessment_report.json
generated HTML assessment report at: /home/ec2-user/migration/assessment/reports/migration_assessment_report.html
Migration assessment completed successfully.
```

```
[ssm-user@ip-10-71-250-57 bin]$ curl http://10.71.250.57:15433/api/migrations
{"migrations":[]}
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by hbhanawat** [comment]
@shubham-yb could you please confirm the behavior?

**Comment by shubham-yb** [comment]
Hi, I attempted to reproduce this issue on my end using the configurations you provided, but I am able to see the migration in the UI.

Voyager version: 1.8.5-rc1

YugabyteDB version: 2024.1.3.0

Voyager command:

```
yb-voyager assess-migration --export-dir ${EXPORT_DIR}         --source-db-type ${SOURCE_DB_TYPE}         --source-db-host ${SOURCE_DB_HOST}         --source-db-user ${SOURCE_DB_USER}         --source-db-schema ${SOURCE_DB_SCHEMA}         --source-db-password ${SOURCE_DB_PASSWORD}         --source-db-name ${SOURCE_DB_NAME} --start-clean t --yes --iops-capture-interval 1
GIT_COMMIT_HASH=4f3afcd389cac1236f0051c38215ae360420fb3e
migrationID: 7913764b-5c57-417c-b735-521c8e8401ea
gathering metadata and stats from 'postgresql' source database...
sleep interval for calculating iops: 1 seconds
Assessment metadata collection started for ''public'' schemas
Collecting db queries summary...
Collecting index to table mapping...
Collecting object_type_mapping...
Collecting table columns count...
Collecting table columns data types...
Collecting table index iops...
Collecting table index sizes...
Collecting table row counts...
Collecting schema information...
Assessment metadata collection completed
gathered assessment metadata files at '/home/ec2-user/a/assessment/metadata'
Generating assessment report...
generated JSON assessment report at: /home/ec2-user/a/assessment/reports/migration_assessment_report.json
generated HTML assessment report at: /home/ec2-user/a/assessment/reports/migration_assessment_report.html
Migration assessment completed successfully.
```

I was able to successfully retrieve the payload:

```
curl http://10.9.15.173:15433/api/migrations
{"migrations":[{"migration_uuid":"7913764b-5c57-417c-b735-521c8e8401ea","migration_name":"Migration_521c8e8401ea","migration_phase":1,"invocation_sequence":2,"source_db":"postgresql","complexity":"N/A","database_name":"a","schema_name":"public","status":"In Progress","invocation_timestamp":"2024-11-11 12:31:12"}]}
```

Additionally I can see the migration on the UI:

<img width="1546" alt="image" src="https://github.com/user-attachments/assets/3547c908-750d-4ab7-ad98-06408b71fda8">



Can you please confirm once that the `CONTROL_PLANE_TYPE` and the `YUGABYTED_DB_CONN_STRING` env vars are properly set as mentioned in the docs? Also can you check if the Voyager log file has any indicators regarding any issues while sending the payload to YugabyteD. You can find the file at this path `export-dir/logs/yb-voyager-assess-migration.log`

**Comment by hbhanawat** [comment]
@jlisthood Closing it based on the comments above. Reopen it in case you hit the issue again.
