### ISSUE TITLE
[Voyager] {NOT VAILD} useage on constrains cause import data fail 

### ISSUE THREAD

**Issue by frg01** [yugabyte/yb-voyager#1895]
Jira Link: [DB-14033](https://yugabyte.atlassian.net/browse/DB-14033)
### Description

1. oracle use the constrains 
```
 TABLESPACE "SYSTEM"  ENABLE NOVALIDATE, 
	 CONSTRAINT "CUSTOMER_CREDIT_LIMIT_MAX" CHECK (credit_limit <= 50000) DEFERRABLE ENABLE NOVALIDATE, 
```
2. migration to yugabytes constrains like 
```
Check constraints:
    "customer_credit_limit_max" CHECK (credit_limit <= 50000::numeric) NOT VALID
```

3. import data faild 
The usage of constrains not checking existing data in Oracle corresponds to NOT VAILD  in PG ,but NOT VAILD has been comleted during the import schema stage, so when importing data next ,data that exceeds the constrains cannot be imported.  

Tips:Before the import data phase ,the tables in the target database do not  have any data.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by priyanshi-yb** [comment]
Hi @frg01 , we have ticket #1829 to handle these type of constraints either by reporting or handling in Voyager itself. So if this is the only issue can you please mark this ticket as duplicate and close?
Thanks!
