### ISSUE TITLE
[Voyager] If  i exec command directly, An execpet will be reported.

### ISSUE THREAD

**Issue by frg01** [yugabyte/yb-voyager#1913]
Jira Link: [DB-14107](https://yugabyte.atlassian.net/browse/DB-14107)
### Description

 yb-voyager archive changes --export-dir ~/export-dir  --delete-changes-without-archiving 1 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbca37a]

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ShivanshGahlot** [comment]
Hey, I was able to replicate the issue by doing this experiment:

1. Created and empty export dir and ran the archive command, it failed with segmentation error
2. Ran export schema in the same export dir and then ran the archive command, was working in this case.

The archive changes command is failing when the export dir is completely empty. Like just an empty folder and nothing has been started. The archive changes command expects that at least the basic directory structure (i.e. folders for metadata, data etc) will be present in the export dir. This structure is made when we run any export command. So, the archive command fails with this nil pointer error when it is unable to find the 'data' folder in the export dir.

We will be adding a check to ensure that archive changes command is only run along with export data
