### ISSUE TITLE
Observing godror WARNING: discrepancy between DBTIMEZONE ("+00:00"=0) and SYSTIMESTAMP ("-04:00"=-400) - set connection timezone, warning

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#200]
Jira Link: [DB-13528](https://yugabyte.atlassian.net/browse/DB-13528)
Hi, I am observing following warning. Can you please suppress or suggest to fix it.
stgres@postgres-VirtualBox:~/demo$ yb-voyager export schema --export-dir .  --source-db-type oracle  --source-db-host 192.168.66.31 --source-db-port 1521  --source-db-user nw --source-db-password oracle --source-db-schema nw --source-db-name orcl  --start-clean

Note: Using current working directory as export directory

Using DB Name for export.

CAUTION: Using --start-clean will overwrite any manual changes done to the exported schema. Do you want to proceed? [Y/N]: Y

export of schema for source type as 'oracle'

godror WARNING: discrepancy between DBTIMEZONE ("+00:00"=0) and SYSTIMESTAMP ("-04:00"=-400) - set connection timezone, see https://github.com/godror/godror/blob/master/doc/timezone.md

oracle version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

exporting       TYPE            done

exporting   SEQUENCE            done

exporting      TABLE            done

exporting    PACKAGE            done

exporting       VIEW            done

exporting    TRIGGER            done

exporting   FUNCTION            done

exporting  PROCEDURE            done

exporting  PARTITION            done

exporting      MVIEW            done

exporting    SYNONYM            done

**Comment by hbhanawat** [comment]
Older issue. Should not be seen now. reopen in case it is seen again.
