### ISSUE TITLE
Please provide an option to generate percentage of successful migration can be possible in the assessment report.

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#201]
Jira Link: [DB-13531](https://yugabyte.atlassian.net/browse/DB-13531)
Hi Team,
Customer would like to capture the following.

Please provide an option to generate percentage of successful migration can be possible in the assessment report.

Can you please help.

Thanks

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant. YugabyteD UI should provide an advanced view.
