### ISSUE TITLE
Please provide a build which works for all linux environment without any problem.

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#205]
Hi Team,
Please provide a build which works for all Linux environment without any problem.

Thanks

**Comment by jamesydb** [comment]
Please make sure we should perform prerequisite check while running any command and if we do not find required packages and dependent software than it should highlight missing objects.

**Comment by kneeraj** [comment]
This may not be possible owing to different libraries and packages required for each flavour of linux. However we are working on a yum, apt, brew installer which should take care of this.
https://github.com/yugabyte/yb-voyager/issues/114
