### ISSUE TITLE
[ORACLE] Import schema for numeric types fail with the message NUMERIC scale 127 must be between 0 and precision 38 (SQLSTATE 22023)

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#207]
**Source table**
create table numeric_size(num_min number(1,-84),num_max number(38,127),numeric_min numeric(1,-84),numeric_max numeric(38,127),float_val FLOAT(5),dec_min_Val dec(1,-84),dec_max_Val dec(38,127),decimal_min_Val decimal(1,-84),decimal_max_Val decimal(38,127));
insert into numeric_size values(0.000000000000000000000000000000000000000000000000000000000000000000000000000000009999,
                               0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234567890123456789012345678901234567,
                               -0.000000000000000000000000000000000000000000000000000000000000000000000000000000009999,
                               0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234567890123456789012345678901234567,
                               123.45,
                               0.000000000000000000000000000000000000000000000000000000000000000000000000000000009999,
                               0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234567890123456789012345678901234567,
                               -0.000000000000000000000000000000000000000000000000000000000000000000000000000000009999,
                               -0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234567890123456789012345678901234567);

**IMPORT SCHEMA ERROR**
importing   TABLE
  ERROR: NUMERIC scale 127 must be between 0 and precision 38 (SQLSTATE 22023)
  STATEMENT: CREATE TABLE numeric_size (
	num_min real,
	num_max decimal(38,127),
	numeric_min real,
	numeric_max decimal(38,127),
	float_val double precision,
	dec_min_val real,
	dec_max_val decimal(38,127),
	decimal_min_val real,
	decimal_max_val decimal(38,127)
) ;
ERROR: NUMERIC scale 127 must be between 0 and precision 38 (SQLSTATE 22023)

**Comment by rahulb-yb** [comment]
YB does not allow numeric/decimal values to have scale greater than precision. As of now, the user has to manually remove this explicit declaration of both scale and precision:
```
num_max decimal(38,127) -> num_max decimal
```

Additional details can be found in the manual review document: https://docs.google.com/document/d/1ZzPGdn2tSHdbqzQ4b-WdXFRedLaiQqun5osV1vAG-CY
