### ISSUE TITLE
Verify the copyCommand generated for table partitions

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#211]
`If copyCommand==""` in line `importData.go` at line 843 
in that case proper handling should be there and if required ERROR out, instead of just logging the info.

**Comment by kneeraj** [comment]
Please elaborate the issue @sanyamsinghal

**Comment by sanyamsinghal** [comment]
Rightnow in case the COPY command is not found for some data file dumped we ignore that.
But the correct/better behavior should be error out in case COPY command is not available. 
TODO: Check the COPY command formation/extraction for table partitions

**Comment by sanyamsinghal** [comment]
covered as part of other tickets
