### ISSUE TITLE
Observing  ERROR logging.go:28 Data export failed: exit status 2  WARNING: an error occurs during data export. Please check what's happen.

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#212]
Jira Link: [DB-13533](https://yugabyte.atlassian.net/browse/DB-13533)
Hi Team, I have encountered following errors while exporting data. Never seen before. Can you please check and help to fix it.

2022-08-05 12:43:39 INFO ora2pg_export_data.go:92 ora2pg STDOUT:
2022-08-05 12:43:39 ERROR ora2pg_export_data.go:93 ora2pg STDERR:
WARNING: an error occurs during data export. Please check what's happen.

2022-08-05 12:43:39 ERROR logging.go:28 Data export failed: exit status 2

WARNING: an error occurs during data export. Please check what's happen.

**Comment by kneeraj** [comment]
Very little information to reproduce this issue. Please provide more details. Is this consistently reproducible?

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant anymore.
