### ISSUE TITLE
yb-voyager does not support lower case table name while exporting data from Oracle using table-list

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#213]
Hi Team, yb-voyager does not support lower case table name based on my observation while exporting data from Oracle using table-list option. Please see below error message.
yb-voyager export data --export-dir .  --source-db-type oracle  --source-db-host ssinghal-dms-oracle.cbtcvpszcgdq.us-west-2.rds.amazonaws.com --source-db-port 1521 --source-db-schema ds21tb --source-db-name dms --source-db-user ds21tb --source-db-password ds2 --parallel-jobs 8 --start-clean --table-list orders,orderlines
Note: Using current working directory as export directory
Using DB Name for export.
export of data for source type as 'oracle'
calculating num of rows to export for each table...
/Failed to query row count of "DS21TB.\"orderlines\"": dpiStmt_execute: ORA-00942: table or view does not exist
[centos@ip-10-9-86-29 ora1tbmig]$  yb-voyager export data --export-dir .  --source-db-type oracle  --source-db-host ssinghal-dms-oracle.cbtcvpszcgdq.us-west-2.rds.amazonaws.com --source-db-port 1521 --source-db-schema ds21tb --source-db-name dms --source-db-user ds21tb --source-db-password ds2 --parallel-jobs 8 --start-clean --table-list ORDERS,ORDERLINES
Note: Using current working directory as export directory
Using DB Name for export.

**Comment by sanyamsinghal** [comment]
As per the internal discussion, the overall behavior should be:
1. Table names without double quotes: convert the names to the case as per db type(Oracle: uppercase, Pg: lowercase, MySQL: case sensitive)
2. Table names with double quotes: don't convert the case (TODO: Explore the scenario for MySQL with double quotes)

**Comment by priyanshi-yb** [comment]
fixed in https://github.com/yugabyte/yb-voyager/pull/407.
