### ISSUE TITLE
[ORACLE] NUMBER is mapped to big_int hence decimals mapped as NUMBERS are not exported

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#215]
**Query used for data creation**
drop table numeric_types_number;
create table numeric_types_number(num_val NUMBER);
insert into numeric_types_number values(123.79);

**Message after import data**
COPY "NUMERIC_TYPES_NUMBER" FROM file "/home/ubuntu/export-dir/oracle_dir/metainfo/data/NUMERIC_TYPES_NUMBER.0.4.4.109.P": ERROR: invalid input syntax for integer: "123.79" (SQLSTATE 22P02)

**Table.sql contents**
CREATE TABLE numeric_types_number (
	num_val bigint
) ;

**Comment by amit-yb** [comment]
@rahulb-yb Can you see if we can add mapping from NUMBER to some other more suitable data type?
