### ISSUE TITLE
[ORACLE] Incorrect values migrated to yugabyte for Binary float/double variables

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#216]
Mapping for **Binary Float/Double** : **NUMERIC**

**Query used** - BINARY FLOAT
create table numeric_types_binary_float(num_val BINARY_FLOAT);
insert into numeric_types_binary_float values(1.17549E-38F); //0.0000000000000000000000000000000000000117549

**Data stored as**
COPY numeric_types_binary_float (num_val) FROM STDIN;
1.17549001E-038 //0.0000000000000000000000000000000000000117549**001** (001 is appended)

********************************************************************************************************************************

**Query used** - BINARY DOUBLE 
create table numeric_types_binary_double(num_val BINARY_DOUBLE);
insert into numeric_types_binary_double values(1.79769313486231E+108); //insert into numeric_types_binary_double values(1.79769313486231E+108); //17976931348623**1**0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Data stored as**
COPY numeric_types_binary_double (num_val) FROM STDIN;
1.7976931348623099E+108 //17976931348623**099**00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 (1 changes to 099)

**Comment by kneeraj** [comment]
Looks like a non-issue. Details to be provided soon.
