### ISSUE TITLE
[ORACLE] Null and '' values are migrated as \N in yugabyte

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#218]
**Query used**
CREATE TABLE LONG_TYPE(long_value LONG);
INSERT INTO LONG_TYPE VALUES('0102030405060708090A0B0C0D0E0F');
INSERT INTO LONG_TYPE VALUES(NULL);
INSERT INTO LONG_TYPE VALUES('');

**Data migrated as**
0102030405060708090A0B0C0D0E0F
\N
\N

**Comment by kneeraj** [comment]
@chetank-yb what if we fire a query with the NOT NULL clause? Does it filters out such rows?

**Comment by kneeraj** [comment]
@chetank-yb gentle reminder

**Comment by chetank-yb** [comment]
The rows get filtered when we query with NOT NULL @kneeraj

**Comment by kneeraj** [comment]
This is as expected then. So closing the bug.
