### ISSUE TITLE
Handle Import if user deletes some rows from the file batch splits.

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#223]
After the retry patch added in PR #220 If a user retries after deleting some row(s) from a batch, yb-voyager will never be able to mark the batch as completed since the rowsAffected needs to match the ones expected to be inserted by the batch.

**Comment by amit-yb** [comment]
This issue is no more applicable. Now we retry until COPY returns without any error (which implies all rows from the batch are imported). We do NOT explicitly check whether number of imported rows count matches with the row count present in file-name.
