### ISSUE TITLE
Revisit Implementation/Behaviour for Index Creation before or after data load.

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#230]
1. Rightnow we create it at the end of import data.
2. Also think about index creation behaviour wrt to table list flags (`--table-list` `--exclude-table-list`)

similar ticket https://github.com/yugabyte/yb-voyager/issues/206

**Comment by kneeraj** [comment]
Make ignore exist flag true by default. "start-clean" should drop the index.

**Comment by amit-yb** [comment]
This issue will be addressed by https://github.com/yugabyte/yb-voyager/issues/228 where we are having a separate phase for "post data load schema import".
