### ISSUE TITLE
Partition data overwritten by export data option

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#232]
Hi Team,
Based on the my observation, if schema contains two different partition tables and both tables cotain similar partition names then csv files overwritten while exporting data. Can you please look into it. I will share the example if you want to test your self.

Thanks

**Comment by sanyamsinghal** [comment]
Fix will be: To enable prefixing the partition names with the parent table name for export from Oracle.

**Comment by jamesydb** [comment]
it's not overwriting but actually skipping the export partitions. Sorry for the wrong details. Please see below output.

2022-08-18 11:55:06 INFO ora2pg_export_data.go:92 ora2pg STDOUT: WARNING: Skipping dumping data to file ./data/PART_FEB2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_MAR2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_JUL2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_JUN2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_JAN2011_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_DEC2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_NOV2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_APR2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_AUG2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_JUN2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_JAN2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_SEP2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_OCT2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_NOV2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_SEP2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_OCT2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_DEC2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_JUL2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_MAY2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_MAR2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_AUG2009_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_APR2010_data.sql, file already exists.
WARNING: Skipping dumping data to file ./data/PART_FEB2010_data.sql, file already exists.

**Comment by sanyamsinghal** [comment]
This has been fixed as part of PRs - #353 and #450. Closing the ticket. 
Please verify with the latest build and reopen the issue if sees any issue.
