### ISSUE TITLE
[Bug] ERROR: Invalid argument: Sending too long RPC message (343812350 bytes) (SQLSTATE XX000)

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#240]
As per the internal conversation: This could be recurring, so retries might not help if the elements in the batch stay the same
Needs to be fixed/handled on the server side.

**Comment by sushantrmishra** [comment]
Summary of the discussion with @lingamsandeep and @kneeraj . 

- Reproducible test scenario or possible get table schema when this scenario happens. 
- Following variable controls the batch size and as a workaround can be tuned to reduce the batch size and avoid this error.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-0e970c36-7fff-aa30-ebd3-c8c8440747ac"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">List of </span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">session variables/ gflags</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> controlling size of the RPC message</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Variable name | Type | Default Value | Description | Comments
-- | -- | -- | -- | --
ROWS_PER_TRANSACTION | Input in the copy from command | 20k | Copy command is broken in multiple transactions, this only tracks the size of each transaction | set optimal values based on the instance type
ysql_session_max_batch_size | Session variable  or GFLAG. Session variable takes precedence | 3072 | Sets the maximum batch size for writes that YSQL can buffer before flushing to tablet servers | set optimal values based on the instance type
ysql_max_in_flight_ops | Session variable | 10000 | Maximum number of in-flight operations allowed from YSQL to tablet servers | set optimal values based on the instance type
 

</div></b>

**Comment by amit-yb** [comment]
yb-voyager now restricts the batch size to 200MB. So that no COPY command is issued by yb-voyager with payload greater than 200MB.
