### ISSUE TITLE
[MYSQL] Check Constraint not showing up/working on the YB side

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#242]
This was the create table schema

`create table  check_constraint_test(
        ID int PRIMARY KEY,
        Name varchar(255) NOT NULL,
        Age int,
        City varchar(255),
        CONSTRAINT CHK_Person CHECK (Age>=18 AND City='Bangalore')
);`

This is the constraint desc on the source

![Image](https://user-images.githubusercontent.com/65844208/185551322-18341c79-2a62-4e6c-b494-3e513177022c.png)

This is the constraint desc on the target

![Image](https://user-images.githubusercontent.com/65844208/185551524-e35a7b29-4fbb-455e-9fb0-bfb87cec8896.png)

This goes ahead fine violating the check constraint

![Image](https://user-images.githubusercontent.com/65844208/185551834-44a507e5-0734-45c9-af3a-2dd4db19a323.png)

**Comment by rahulb-yb** [comment]
The user will have to manually add the check constraints (in the case of MySQL). Refer to the manual review doc for additional details: https://docs.google.com/document/d/1ZzPGdn2tSHdbqzQ4b-WdXFRedLaiQqun5osV1vAG-CY
