### ISSUE TITLE
[MySQL] Sequence Number Start Value

### ISSUE THREAD

**Issue by seethb** [yugabyte/yb-voyager#245]
In MySQL Auto Increment explicitly assign 0 to the column to generate the next sequence number where Voyager converts the same value and generates the table script whereas YB needs to start the sequence from 1. the Table generation scripts fails for such tables having sequence number as 0 as a starting point. 

ALTER SEQUENCE id_seq RESTART WITH 0;

we need to manually go to each line of table.sql and change to ALTER SEQUENCE actor_id_seq RESTART WITH 1;

Can this be fixed?

**Comment by sanyamsinghal** [comment]
@seethb can you please share the steps to reproduce this issue (specially the steps to create same on source side)

**Comment by seethb** [comment]
The step is simple, my source DB is MySQL and just ran the export schema and when I do the import schema its started failing as the Alter sequence statements expect with 1 in YBDB where as 0 is supported in MySQL.

**Comment by sanyamsinghal** [comment]
@seethb please share the DDLs to create a similar structure on the source db side(MySQL)

**Comment by amit-yb** [comment]
@seethb Will this issue be applicable only for the empty tables? For tables containing data, the sequence number will be appropriately set by yb-voyager, isn't it?

**Comment by amit-yb** [comment]
@rahulb-yb, please reproduce the issue first and then add a check in the `analyze-schema` command.

**Comment by rahulb-yb** [comment]
@seethb Even when I attempt to create a sequence which explicitly begins with 0, the sequence continues to begin with 1. I get the following DDL in my case when I export schema:
`ALTER SEQUENCE id_seq RESTART WITH 2;`

If I wish to start the sequence with an arbitrary positive integer, for eg. id_seq should start with 100, I get the following DDL exported:
`ALTER SEQUENCE id_seq RESTART WITH 101;`

It will be helpful if you can share the DDL that was used to produce this issue

**Comment by rahulb-yb** [comment]
Closing this issue, a ticket has been raised on [ora2pg GH](https://github.com/darold/ora2pg/issues/1496) owing to lack of directives in the configuration file, compounded with inconsistent reproducibility of this issue.

Refer to the manual review guideline doc for additional information/solutions for this issue: https://docs.google.com/document/d/1ZzPGdn2tSHdbqzQ4b-WdXFRedLaiQqun5osV1vAG-CY

**Comment by rahulb-yb** [comment]
Closing this ticket, ticket mentioned above has been addressed
