### ISSUE TITLE
[MySQL] Default Value with Period

### ISSUE THREAD

**Issue by seethb** [yugabyte/yb-voyager#247]
In MySQL we have a column `s_hier_id` varchar(64) NOT NULL DEFAULT '.', after migration the "Quote" is missing it just . [period] the table.sql is failing as it ignores that as a default value and says incorrect syntax near .

we need to manually go to table.sql and fix the single quote before migration.

Can this be fixed please?

**Comment by amit-yb** [comment]
@shubham-yb Make an entry in the manual review guideline document and file a ticket with ora2pg.

**Comment by shubham-yb** [comment]
Fixed by ora2pg in their commit `b0dc8262a4b5b8759da5ec9408b29a52aedaa52d` and tested.
