### ISSUE TITLE
`schema version mismatch` from DB while creating index after data import

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#250]
```
ERROR: Aborted: ERROR:  Query error: schema version mismatch for table 00004005000030008000000000004590: expected 1, got 0 
```

Steps : 
1. Create tables on source with unique index. 
2. Use yb-voyager to export schema followed by data and import schema
3. Perform import data.

Expected : Migration must be successful.
Actual: Error displayed on performing import data

Please find the [Schema and the Error logs here](https://docs.google.com/document/d/1sCHJSAOMUv8KgRlWMQHoizq_RyaC1czq5i-UmUfd6Uc/edit)

**Comment by sanyamsinghal** [comment]
cc @sushantrmishra

**Comment by sanyamsinghal** [comment]
DB side Ticket: https://github.com/yugabyte/yugabyte-db/issues/13073
