### ISSUE TITLE
[YugabyteDB] Add automation test for multiple server version starting 2.12

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#251]
Currently, our automation tests run for`2.12.3` release only.
We should run those automation tests for at least one release for each major version starting: `2.12`, `2.13`, `2.14`, `2.15` and so on... 
It is very important to avoid any surprises with a new db release.

These extra tests can run once a day if not with every PR

**Comment by amit-yb** [comment]
Fixed by: 
```
commit d0ff5852ddeac5e1f46f36190516831a20b86942
Author: Rahul Barigidad <72571621+rahulb-yb@users.noreply.github.com>
Date:   Wed Sep 28 14:53:30 2022 +0530

    Added strategy matrix to pull latest yugabyteDB docker images (#359)
```

**Comment by amit-yb** [comment]
Reopening this ticket as @rahulb-yb is going to revisit one aspect of the implementation.
