### ISSUE TITLE
[ORACLE] Error observed while migrating tables with bit map index

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#252]
Create table with a bit map index and migrate the schema and the data.

Expected : Migration should be successful.
Actual : Error on migration.

**Test data and schema used** : https://docs.google.com/document/d/1mz3yRlMIWS1YAoBKgr3DneswSU0w4PlDbsI3FZKOE8Y/edit

**Comment by amit-yb** [comment]
@chetank-yb Can you please try suggestions given in https://stackoverflow.com/questions/32138996/why-error-occurred-while-creating-gin-index ? If creating the `pg_trgm` extension helps, then we will try to accommodate this issue in yb-voyager.

**Comment by amit-yb** [comment]
If there is a gin index, either yb-voyager or the user will have to run the `CREATE EXTENSION pg_trgm` command.

**Comment by chetank-yb** [comment]
@amit-yb , this issue is linked to https://github.com/yugabyte/yb-voyager/issues/252. I guess we can close this one and track https://github.com/yugabyte/yb-voyager/issues/252.

**Comment by rahulb-yb** [comment]
> @amit-yb , this issue is linked to #252. I guess we can close this one and track #252.

Hey @chetank-yb , issue #252 is this one, did you mean to link some other issue?
