### ISSUE TITLE
Installation scripts skips the pg_dump installation if already present in the system

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#256]
Installation Scripts skips the installation of the `pg_dump` if `pg_dump` is already present in the system with lower version like `9.2`. Due to which it was giving this error while I tried `export schema`  command-

`yb-voyager export schema --export-dir ${EXPORT_DIR}         --source-db-type ${SOURCE_DB_TYPE}         --source-db-host ${SOURCE_DB_HOST}         --source-db-user ${SOURCE_DB_USER}         --source-db-password ${SOURCE_DB_PASSWORD}         --source-db-name ${SOURCE_DB_NAME}`

Error -
> export of schema for source type as 'postgresql'
> postgresql version: 11.13
> exporting the schema           error
> data export unsuccessful: exit status 1

Error in `yb-voyager.log` - 

> pg_dump: server version: 11.0 ; pg_dump version: 9.2.
> pg_dump: aborting because of server version mismatch

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant because of the recent changes
