### ISSUE TITLE
error in scanning rows of yb_servers(): number of field descriptions must equal number of destinations, got 9 and 8

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#259]
Hi Team, Encountering following error while importing specific table . Please review following error and do let me know if you need anything.

yb-voyager import data --export-dir /home/centos/ora1tbmig/customer/  --target-db-host 172.151.32.95 --target-db-port 5433 --target-db-schema ds21tb --target-db-user yugabyte --t
arget-db-password yugabyte  --start-clean --target-db-name ds21tb --parallel-jobs 8 --table-list customers
import of data in "ds21tb" database started
Target YugabyteDB version: 11.2-YB-2.15.3.0-b0
error in scanning rows of yb_servers(): number of field descriptions must equal number of destinations, got 9 and 8

**Comment by sanyamsinghal** [comment]
The issue in yb-voyager got introduced in version starting `2.15.3`in which a new column has been added. 
We are tracking the task for this and will be fixed very soon.

**Comment by priyanshi-yb** [comment]
#265 Resolves this Issue.
