### ISSUE TITLE
Export Schema - Index Names are duplicated

### ISSUE THREAD

**Issue by seethb** [yugabyte/yb-voyager#260]
While we run Export Schema from MySQL as source DB, in the INDEXES_table.sql of schema directory generate duplicate index name for different tables like below.

CREATE INDEX fk_actor_contact_detail_actor1_idx ON actor__contact_detail__mapping (actor_id);
CREATE INDEX fk_actor_contact_detail_actor1_idx ON actor__document__mapping (actor_id);

CREATE INDEX fk_office_contact_detail_contact_detail1_idx ON actor__contact_detail__mapping (contact_detail_id);
CREATE INDEX fk_office_contact_detail_contact_detail1_idx ON office__contact_detail__mapping (contact_detail_id);
CREATE INDEX fk_office_contact_detail_contact_detail1_idx ON user__contact_detail__mapping (contact_detail_id);

CREATE INDEX fk_user_device_device1_idx ON user__device__mapping (device_id);
CREATE INDEX fk_user_device_device1_idx ON office__device__mapping (device_id);

Can this be fixed please? during Import schema these are not possible to be executed after Import data only this can be tested

**Comment by sanyamsinghal** [comment]
Hi @seethb this is a known issue and tracked here - https://github.com/yugabyte/yb-voyager/issues/136 with more details.
The major reason is that in MySQL, index names are unique under each table not schema/database.

Currently, the way is to edit the DDLs during the review of schema or analyze-schema phase, which will be taken care of in new releases of yb-voyager before GA
