### ISSUE TITLE
Encountering load data descriptor file: open /home/centos/ora1tbmig/orderlines/metainfo/dataFileDescriptor.json: no such file or directory error

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#261]
Jira Link: [DB-13537](https://yugabyte.atlassian.net/browse/DB-13537)
Hi Team,

I am encountering following error while importing the data for specific table.

load data descriptor file: open /home/centos/ora1tbmig/orderlines/metainfo/dataFileDescriptor.json: no such file or directory

Can you please help to fix the above mentioned error.

Thanks
Jaimin

**Comment by amit-yb** [comment]
Hello @jamesydb, can you please share the log file?

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant. reopen in case it is seen again.
