### ISSUE TITLE
Encountering ERROR: invalid byte sequence for encoding "UTF8": 0xc9 0x55 (SQLSTATE 22021)

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#262]
Jira Link: [DB-13538](https://yugabyte.atlassian.net/browse/DB-13538)
Hi Team,

I am trying to load customer file using yb-voyager but it's failing with following error.

yb-voyager import data file --export-dir . --data-dir "/tmp" --target-db-host 172.151.36.235 --target-db-port 5433 --target-db-user yugabyte  --start-clean --target-db-name tpcds --parallel-jobs 1 --file-table-map "customer:customer" --delimiter "|" --target-db-password yugabyte
Note: Using current working directory as export directory
import of data in "tpcds" database started
Target YugabyteDB version: 11.2-YB-2.14.0.0-b0
Truncating all tables: [customer]
Preparing to import the tables: [customer]
customer [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0.00% 0s
COPY "customer" FROM file "./metainfo/data/customer.1.100000.100000.13187063.P": ERROR: invalid byte sequence for encoding "UTF8": 0xc9 0x55 (SQLSTATE 22021)

I am able to load the same file using copy command on psql prompt. 

Loading customer...
COPY 500000

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant. reopen in case it is seen again.
