### ISSUE TITLE
Bug: Fix Import Data Status command output in case of import data file command

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#271]
Right now the output of the status command displays the `TOTAL_ROWS` and `IMPORTED_ROWS` while in case of the `import data file` command that is not true. There we make use of file size for estimation of the progress.
Fix: It should something like `TOTAL_SIZE` `IMPORTED_SIZE` in that case

**Comment by ShivanshGahlot** [comment]
Merged the required changes
