### ISSUE TITLE
[MYSQL] Domino effect of failure of CREATE INDEX after import data

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#276]
If any of the CREATE INDEX fails, all the rest below it fail as well.

But it still shows up at  `cat INDEXES_table.sql `  and not on the target.

![Image](https://user-images.githubusercontent.com/65844208/187466357-15753e8f-3003-4dd5-b56c-97699f6afed0.png)

This is the target.

![Image](https://user-images.githubusercontent.com/65844208/187466767-d78cb1a0-60ce-4437-94db-14a240ed9fc2.png)

**Comment by amit-yb** [comment]
This is an expected behaviour. yb-voyager exits on first DDL error. Pass `--continue-on-error` to continue with the remaining errors.

**Comment by shubham-yb** [comment]
Worked after adding the flag.
