### ISSUE TITLE
[MYSQL] Functional/Expression indexes fail to migrate

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#277]
This is the schema I used.

```
CREATE TABLE `exp_index_test` (
  `emp_no` int NOT NULL,
  `salary` int,
  `from_date` date NOT NULL,
  `to_date` date NOT NULL,
  PRIMARY KEY (`emp_no`)
);

insert into exp_index_test values(3,1000,'1985-07-06','1985-09-28');
insert into exp_index_test values(4,1000,'1985-07-06','1985-09-28');

CREATE INDEX exp_ind ON exp_index_test((year(`to_date`))); 
```

Source:

![Image](https://user-images.githubusercontent.com/65844208/187469982-7515f5c9-36fc-4d55-8b0f-f4fa125d536d.png)

Target:

![Image](https://user-images.githubusercontent.com/65844208/187469783-cfb6baa5-e376-485c-b308-47e3fa1c667f.png)

This is the error after import data.

![Image](https://user-images.githubusercontent.com/65844208/187469103-f3a4ebcd-cab8-4438-b752-1e459794e5ae.png)

**Comment by amit-yb** [comment]
@shubham-yb Add the issue to Manual review guideline document and file a ticket with ora2pg.

**Comment by shubham-yb** [comment]
The user will have to manually add the index. Refer to the manual review doc for additional details: https://docs.google.com/document/d/1ZzPGdn2tSHdbqzQ4b-WdXFRedLaiQqun5osV1vAG-CY

**Comment by shubham-yb** [comment]
The issue was put up in Ora2Pg and changes were made.
[Commit](https://github.com/darold/ora2pg/commit/24a4761fdd2d0e6f167807e3fba0576c5f0af491)

So the format change is going through now, but there's an issue with the oblique quotes while importing.

Here is a simple schema example:

```
create table func_check (
	id int primary key auto_increment,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
);

CREATE INDEX idx_last_name ON func_check((lower(last_name)));
```

The error now,

```
creating indexes           
    ERROR: operator does not exist: ` character varying (SQLSTATE 42883)
    STATEMENT: CREATE INDEX idx_ic_last_name ON view_table1 (lower(`last_name`));
```
This wasn't there earlier.

The import goes through if we remove the oblique quotes.
Reopening this just in case voyager can help in this regard.
Or we'll document it.

**Comment by shubham-yb** [comment]
We'll document it on Manual Review Doc
