### ISSUE TITLE
[MYSQL] Descending Index fails to migrate

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#278]
This is the schema I used

```
create table desc_index_test(id int primary key, f_name varchar(20),l_name varchar(20),val boolean);

insert into desc_index_test values(1,'abc','def',true);
insert into desc_index_test values(2,'abc','vfd',true);
insert into desc_index_test values(3,'ggg','def',false);

CREATE INDEX desc_ind ON desc_index_test(f_name desc); 
```

The Index migrates but ignores the **DESC** .

![Image](https://user-images.githubusercontent.com/65844208/187591291-27aa49ad-7fd4-4570-8cb5-bdcc9a677fe8.png)

This is the target.

![Image](https://user-images.githubusercontent.com/65844208/187591389-7a9d4ff4-72d6-4a89-8222-bdd2a7b11f74.png)

Expected output:

` "desc_ind" lsm (f_name DESC)`

**Comment by amit-yb** [comment]
Good catch! 👍 
@rahulb-yb Can you please file a ticket in ora2pg repo. This issue cannot be handled in yb-voyager.

**Comment by shubham-yb** [comment]
The user will have to manually add the index. Please refer to the manual review doc for additional details: https://docs.google.com/document/d/1ZzPGdn2tSHdbqzQ4b-WdXFRedLaiQqun5osV1vAG-CY
