### ISSUE TITLE
[ORACLE] Partition with Index data not migrated

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#300]
**SCHEMA**

CREATE TABLE ORDERS_INTERVAL_PARTITION
  (
    order_id NUMBER 
             GENERATED BY DEFAULT AS IDENTITY START WITH 106 ,
    customer_id NUMBER( 6, 0 ) NOT NULL, -- fk
    status      VARCHAR( 20 ) NOT NULL ,
    salesman_id NUMBER( 6, 0 )         , -- fk
    order_date  DATE NOT NULL   ,
    CONSTRAINT pk_order_id_cust_id 
        PRIMARY KEY(order_id,order_date),
    CONSTRAINT fk_orders_customers_interval_partition 
      FOREIGN KEY( customer_id )
      REFERENCES customers( customer_id )
      ON DELETE CASCADE,
    CONSTRAINT fk_orders_employees_interval_partition 
      FOREIGN KEY( salesman_id )
      REFERENCES employees( employee_id ) 
      ON DELETE SET NULL
  )
PARTITION BY RANGE (order_date) 
  INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
    ( PARTITION INTERVAL_PARTITION_LESS_THAN_2015 VALUES LESS THAN (TO_DATE('1-1-2015', 'DD-MM-RR')),
      PARTITION INTERVAL_PARTITION_LESS_THAN_2016 VALUES LESS THAN (TO_DATE('1-1-2016', 'DD-MM-RR')),
      PARTITION INTERVAL_PARTITION_LESS_THAN_2017 VALUES LESS THAN (TO_DATE('1-7-2017', 'DD-MM-RR')),
      PARTITION INTERVAL_PARTITION_LESS_THAN_2018 VALUES LESS THAN (TO_DATE('1-1-2018', 'DD-MM-RR')) );

Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (105,1,'Pending',54,to_date('17-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (44,2,'Pending',55,to_date('20-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (101,3,'Pending',55,to_date('03-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (1,4,'Pending',56,to_date('15-OCT-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (5,5,'Canceled',56,to_date('09-APR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (28,6,'Canceled',57,to_date('15-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (87,7,'Canceled',57,to_date('01-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (4,8,'Shipped',59,to_date('09-APR-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (41,9,'Shipped',59,to_date('11-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (82,44,'Shipped',60,to_date('03-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (102,45,'Shipped',61,to_date('20-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (26,46,'Shipped',62,to_date('16-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (43,47,'Shipped',62,to_date('02-MAY-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (53,48,'Shipped',62,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (81,49,'Shipped',62,to_date('13-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (83,16,'Shipped',62,to_date('02-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (93,17,'Shipped',62,to_date('27-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (94,1,'Shipped',62,to_date('27-OCT-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (79,2,'Shipped',64,to_date('14-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (80,3,'Shipped',64,to_date('13-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (2,4,'Shipped',null,to_date('26-APR-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (3,5,'Shipped',null,to_date('26-APR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (6,6,'Shipped',null,to_date('09-APR-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (7,7,'Shipped',null,to_date('15-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (8,8,'Shipped',null,to_date('14-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (9,9,'Shipped',null,to_date('14-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (10,44,'Pending',null,to_date('24-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (11,45,'Shipped',null,to_date('29-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (12,46,'Shipped',null,to_date('29-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (13,47,'Shipped',null,to_date('29-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (14,48,'Shipped',null,to_date('28-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (15,49,'Shipped',null,to_date('27-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (16,16,'Pending',null,to_date('27-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (17,17,'Shipped',null,to_date('27-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (18,18,'Shipped',null,to_date('16-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (19,19,'Shipped',null,to_date('27-MAY-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (20,20,'Shipped',null,to_date('27-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (21,21,'Pending',null,to_date('27-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (22,22,'Canceled',null,to_date('26-MAY-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (23,23,'Shipped',null,to_date('07-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (24,41,'Shipped',null,to_date('07-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (25,42,'Shipped',null,to_date('24-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (27,43,'Canceled',null,to_date('16-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (29,44,'Shipped',null,to_date('14-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (30,45,'Shipped',null,to_date('12-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (31,46,'Canceled',null,to_date('12-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (32,47,'Shipped',null,to_date('09-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (33,48,'Shipped',null,to_date('07-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (34,49,'Shipped',null,to_date('12-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (35,50,'Shipped',null,to_date('05-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (36,51,'Shipped',null,to_date('05-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (37,52,'Shipped',null,to_date('19-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (38,53,'Canceled',57,to_date('31-MAY-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (39,54,'Shipped',62,to_date('22-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (40,55,'Shipped',62,to_date('11-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (42,56,'Canceled',64,to_date('03-MAY-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (45,57,'Shipped',64,to_date('20-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (46,58,'Pending',62,to_date('20-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (47,59,'Canceled',62,to_date('10-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (48,60,'Canceled',64,to_date('10-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (49,61,'Shipped',55,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (50,62,'Pending',55,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (51,63,'Shipped',59,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (52,64,'Shipped',60,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (54,65,'Shipped',56,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (55,66,'Pending',59,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (56,67,'Canceled',55,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (57,68,'Shipped',57,to_date('24-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (58,69,'Shipped',57,to_date('24-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (59,70,'Shipped',59,to_date('29-JUN-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (60,1,'Shipped',62,to_date('30-JUN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (61,2,'Shipped',54,to_date('30-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (62,3,'Shipped',62,to_date('30-JUN-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (63,4,'Shipped',61,to_date('30-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (64,5,'Shipped',64,to_date('21-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (65,6,'Shipped',64,to_date('21-JUN-13','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (66,7,'Canceled',61,to_date('21-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (67,8,'Canceled',61,to_date('14-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (68,9,'Pending',null,to_date('13-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (69,44,'Canceled',54,to_date('17-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (70,45,'Canceled',61,to_date('21-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (71,46,'Shipped',54,to_date('21-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (72,47,'Shipped',64,to_date('17-FEB-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (73,48,'Shipped',null,to_date('17-FEB-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (74,49,'Shipped',64,to_date('10-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (75,16,'Shipped',null,to_date('10-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (76,17,'Shipped',55,to_date('10-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (77,1,'Shipped',60,to_date('02-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (78,2,'Pending',64,to_date('14-DEC-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (84,3,'Shipped',64,to_date('01-DEC-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (85,4,'Pending',55,to_date('01-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (86,5,'Pending',60,to_date('30-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (88,6,'Shipped',61,to_date('01-NOV-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (89,7,'Shipped',55,to_date('27-OCT-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (90,8,'Pending',55,to_date('28-OCT-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (91,9,'Pending',56,to_date('28-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (92,44,'Shipped',59,to_date('28-OCT-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (95,45,'Shipped',59,to_date('19-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (96,46,'Shipped',56,to_date('14-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (97,47,'Canceled',60,to_date('12-JUL-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (98,48,'Shipped',55,to_date('18-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (99,49,'Shipped',60,to_date('07-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (100,16,'Pending',54,to_date('05-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (103,17,'Pending',64,to_date('08-FEB-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (104,18,'Shipped',60,to_date('01-FEB-17','DD-MON-RR'));

COMMIT;

********************************************************************************************************************************
**Data in yugabyte cluster after migration**

![Image](https://user-images.githubusercontent.com/100332069/188473279-7f05903d-b059-4d20-b4bd-9508b3f54d68.png)

********************************************************************************************************************************

**Comment by sanyamsinghal** [comment]
Hi @chetank-yb please confirm this once more with the new branch. Let me know if still exists.

**Comment by chetank-yb** [comment]
Issue validated and closed as it not reproducible anymore.
