### ISSUE TITLE
Table with Autogenerate Primary Key column but data is skipped in import data file

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#303]
In case there is a table with column as autogenerated primary key and table data needs to be imported.

But consider a case that column's data is ignored/skipped during import data considering it will be auto populated and the rows contains only the other columns data, not this one.

So for this scenario, import data can be done using `import data file` command with `--has-header` flag having name of all the columns except this one.
So, in that case `import data file` command needs to handle this, especially the scenario of restart and start-clean where the value for autogenerated column needs to be reset on start-clean

**Comment by amit-yb** [comment]
@sanyamsinghal We have an implicit assumption that the exported data files can be imported using COPY command without any column mismatch (order of the columns, presence/absence of columns etc.) with target table.

If user makes any non-compatible changes to target table schema (e.g. add/remove columns) or change the number/order of the columns in the data file, then the normal `import data` workflow cannot be used. User will HAVE to use the `import data file` command and handle the discrepancy on their own.
