### ISSUE TITLE
[MYSQL] Auto-generated columns not migrated

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#315]
Auto Generated column on MYSQL is not getting migrated and so the rows are not getting generated on the target

This is the schema I used:

```
drop table if exists auto_gen;

create table auto_gen (
	id int primary key auto_increment,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	fullname varchar(101) GENERATED ALWAYS AS (CONCAT(first_name,' ',last_name)),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
);
```

This is the exported schema:

```
CREATE TABLE auto_gen (
	id serial,
	first_name varchar(50),
	last_name varchar(50),
	fullname varchar(101),
	email varchar(50),
	gender varchar(50),
	ip_address varchar(20),
	PRIMARY KEY (id)
) ;
```

Table description on the source:

![Image](https://user-images.githubusercontent.com/65844208/189651268-8f324447-8bf4-4461-a22d-dedfb26742b6.png)

Table description on the target:

![Image](https://user-images.githubusercontent.com/65844208/189651399-1f29ab7d-abed-4935-85b1-feab3d4c2002.png)

**Comment by shubham-yb** [comment]
Tried with a simple numeric auto generated column as well. Didn't work. Not a voyager issue. Yugabyte-DB doesn't support it yet it seems because the same schema worked for Postgres but not YB.

Just for reference the schema I used was:

```
drop table if exists auto_price;

create table auto_price (
	id INT,
	first_name VARCHAR(50),
	gender VARCHAR(50),
	price_dollar DECIMAL(7,2),
    price_pound DECIMAL(7,2) generated always as (price_dollar * 0.22) STORED
);

```

**Comment by rahulb-yb** [comment]
Did some digging, generated columns are supported from PG12 and up. YB is unable to support generated columns regardless, we will have to file an issue both on ora2pg and add a check for generated columns (if any) in analyze schema.

Relavant issues:
https://github.com/yugabyte/yugabyte-db/issues/5805
https://github.com/yugabyte/yugabyte-db/issues/9797

**Comment by shubham-yb** [comment]
I have put up the issue on ora2pg. 

[Issue link](https://github.com/darold/ora2pg/issues/1502#issue-1374051992)

**Comment by shubham-yb** [comment]
https://github.com/yugabyte/yb-voyager/issues/355
