### ISSUE TITLE
[Documentation] Modify the Performance page on docs with new Guidelines

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#326]
Modify the Performance page with new Guidelines about perf numbers for the better perfomance in Migration.

**Comment by priyanshi-yb** [comment]
Updated the perf docs page in this documentation - https://docs.google.com/document/d/1MPLCcC-V40ddPD0YA-qY8K_8FDLVy9iNrhKRUVxQtB8/edit?usp=sharing

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant anymore.
