### ISSUE TITLE
[ORACLE] Foreign Key with constraint ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE fails in import schema

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#331]
Jira Link: [DB-13499](https://yugabyte.atlassian.net/browse/DB-13499)
Please find the error logs here - https://docs.google.com/document/d/1yq_GRz4GsES3MdaW-QV_scUUYDksmC6Djn7qhVkmoHY/edit

**Tables**
PROMPT Creating tables 

create table customers (
  customer_id     integer generated by default on null as identity,
  email_address   varchar2(255 char) not null,
  full_name       varchar2(255 char) not null)
;

create table stores (
  store_id          integer generated by default on null as identity ,
  store_name        varchar2(255 char) not null,
  web_address       varchar2(100 char),
  physical_address  varchar2(512 char),
  latitude          number,
  longitude         number,
  logo              blob,
  logo_mime_type    varchar2(512 char),
  logo_filename     varchar2(512 char),
  logo_charset      varchar2(512 char),
  logo_last_updated date)
;

create table products (
  product_id         integer generated by default on null as identity ,
  product_name       varchar2(255 char) not null,
  unit_price         number(10,2),
  product_details    blob,
  product_image      blob,
  image_mime_type    varchar2(512 char),
  image_filename     varchar2(512 char),
  image_charset      varchar2(512 char),
  image_last_updated date)
;

create table orders (
  order_id        integer
                  generated by default on null as identity,
  order_datetime  timestamp not null,
  customer_id     integer not null,
  order_status    varchar2(10 char) not null,
  store_id        integer not null)
;

create table shipments (
  shipment_id          integer
                       generated by default on null as identity,
  store_id             integer not null,
  customer_id          integer not null,
  delivery_address     varchar2(512 char) not null,
  shipment_status      varchar2(100 char) not null)
;

create table order_items (
  order_id        integer not null,
  line_item_id    integer not null,
  product_id      integer not null,
  unit_price      number(10,2) not null,
  quantity        integer not null,
  shipment_id     integer)
;

create table inventory (
  inventory_id          integer
                        generated by default on null as identity,
  store_id              integer not null,
  product_id            integer not null,
  product_inventory     integer not null)
;

PROMPT Creating indexes

create index customers_name_i on customers ( full_name );
create index orders_customer_id_i on orders ( customer_id );
create index orders_store_id_i on orders ( store_id );
create index shipments_store_id_i on shipments ( store_id );
create index shipments_customer_id_i on shipments ( customer_id );
create index order_items_shipment_id_i on order_items ( shipment_id );
create index inventory_product_id_i on inventory ( product_id );

**CONSTRAINTS**
PROMPT Add constraints to tables

alter table customers add constraint customers_pk primary key (customer_id);

alter table customers add constraint customers_email_u unique (email_address);

alter table stores add constraint stores_pk primary key (store_id);

alter table stores add constraint store_name_u unique (store_name);

alter table stores add constraint store_at_least_one_address_c
  check (
    web_address is not null or physical_address is not null
  );

alter table products add constraint products_pk primary key (product_id);

alter table products add constraint products_json_c
                     check ( product_details is json );

alter table orders add constraint orders_pk primary key (order_id);

alter table orders add constraint orders_customer_id_fk
   foreign key (customer_id) references customers (customer_id);

alter table orders add constraint  orders_status_c
                  check ( order_status in
                    ( 'CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED'));

alter table orders add constraint orders_store_id_fk foreign key (store_id)
   references stores (store_id);

alter table shipments add constraint shipments_pk primary key (shipment_id);

alter table shipments add constraint shipments_store_id_fk
   foreign key (store_id) references stores (store_id);

alter table shipments add constraint shipments_customer_id_fk
   foreign key (customer_id) references customers (customer_id);

alter table shipments add constraint shipment_status_c
                  check ( shipment_status in
                    ( 'CREATED', 'SHIPPED', 'IN-TRANSIT', 'DELIVERED'));

alter table order_items add constraint order_items_pk primary key ( order_id, line_item_id );

alter table order_items add constraint order_items_order_id_fk
   foreign key (order_id) references orders (order_id);

alter table order_items add constraint order_items_shipment_id_fk
   foreign key (shipment_id) references shipments (shipment_id);

alter table order_items add constraint order_items_product_id_fk
   foreign key (product_id) references products (product_id);

alter table order_items add constraint order_items_product_u unique ( product_id, order_id );

alter table inventory add constraint inventory_pk primary key (inventory_id);

alter table inventory add constraint inventory_store_product_u unique (store_id, product_id);

alter table inventory add constraint inventory_store_id_fk
   foreign key (store_id) references stores (store_id);

alter table inventory add constraint inventory_product_id_fk
   foreign key (product_id) references products (product_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

**Comment by kneeraj** [comment]
This should go away with @amit-yb 's change of separating the fk constraint addition phase.

**Comment by hbhanawat** [comment]
Closing it based on Neeraj's comments.
