### ISSUE TITLE
[MYSQL] --target-db-schema flag fails for case sensitive schema names

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#334]
If we create a schema in the YB side with a case sensitive name, and pass the env variable with the same, the `import schema` fails with error.

Steps to reproduce:

1. Create a schema on the target with case sensitive name example: XYZ, Xyz.
2. Pass the same in the env variable of `TARGET_DB_SCHEMA`.
3. Try importing into that schema using the `--target-db-schema` flag.

Corresponding error:

![Image](https://user-images.githubusercontent.com/65844208/191436375-32526ad7-ef19-4b5c-b79a-776fe457b869.png)

**Comment by amit-yb** [comment]
The way we have implemented voyager, case-sensitive names on the target are not supported yet. Maybe, in future we may. But for now, this is a not-applicable test case. So closing this ticket.
