### ISSUE TITLE
Documentation of using table_name of Source DB with --table-list

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#339]
Jira Link: [DB-13507](https://yugabyte.atlassian.net/browse/DB-13507)
Document that the table names passed in the `--table-list` flag should be according to Source DB table names with same case.

**Comment by priyanshi-yb** [comment]
Handled in https://github.com/yugabyte/yb-voyager/pull/407. No need to document now.

**Comment by priyanshi-yb** [comment]
#407, handles in import data but we still need to document for export data as that is a know thing, to pass table names as is from source in the `--table-list` flag at the time of export data.

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant anymore. Please reopen with comments in case of disagreement.
