### ISSUE TITLE
[MYSQL] Functions only get exported when written in a particular format

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#341]
This was observed while testing the `functions` schema object in MYSQL. The functions were getting exported only when defined in a particular format. 

Let's take the example of a function to add two numbers.

A function defined like:

```
CREATE FUNCTION add_two(num1 int,num2 int)
  RETURNS int
    DETERMINISTIC
  RETURN num1+num2;
```

Won't export.

But a function for the same task defined as:

```
delimiter /
CREATE FUNCTION add_two2 (n1 int,n2 int)
  RETURNS int
   DETERMINISTIC
    BEGIN
     DECLARE sum_two int;
       set sum_two=n1+n2;
     RETURN sum_two;
    END/
 
```

Gets exported.

**Comment by shubham-yb** [comment]
A commit has been made by ora2pg in this regard.
Commit:
https://github.com/darold/ora2pg/commit/e13ab160c3b5a162c83f8a6c97e62deb41d48e73

**Comment by kneeraj** [comment]
Just needs verification.
