### ISSUE TITLE
Update the installer script to use the latest ora2pg code

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#350]
Jira Link: [DB-13500](https://yugabyte.atlassian.net/browse/DB-13500)
A couple of fixes have been done in ora2pg recently based on our report. So we should latest master instead of the `23.1` release done in Feb 2022.

Some of those commits are:
1. darold/ora2pg@e13ab16
2. https://github.com/darold/ora2pg/commit/a17e1652c63babdfbee7b55595623bc8e59559c8
3. https://github.com/darold/ora2pg/commit/7a01b2d8f46a6f995842ac142a75a4c6acdfeac1
4. https://github.com/darold/ora2pg/commit/70498fccc1af7e8c1ff5c642b3de15e5d1f615d0
5. https://github.com/darold/ora2pg/commit/59028d196fbde077af7f158b3afb33ebe54f0e2a
6. https://github.com/darold/ora2pg/commit/9ec5c596870f6566a3ae1c53a6698c299d56c2b6
7. https://github.com/darold/ora2pg/commit/081f5f813250000fa4fdd16d267bf3e26ea03efc

**Comment by hbhanawat** [comment]
Being tracked as an IDEA. cc: @ymahajan
