### ISSUE TITLE
Fewer number of rows in the Database after import of more than 350M data with higher parallelism of 200

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#354]
Jira Link: [DB-13498](https://yugabyte.atlassian.net/browse/DB-13498)
We are experiencing the missing rows in the database from `count(*)` after ingesting the data for 350M with higher parallelism of 200 or above. `rows affected` and `tuples_processed` in the `pg_stat_copy_progress`  in the YB Voyager logs are giving the correct count of rows.  

DB side Ticket - https://github.com/yugabyte/yugabyte-db/issues/14113

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant anymore.
