### ISSUE TITLE
Rows reported by import data status if user deletes some rows from a split

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#360]
Jira Link: [DB-13506](https://yugabyte.atlassian.net/browse/DB-13506)
Currently, if the user removes some rows from a split/batch of the table the import data will go through and complete. But the rows reported by the `import data status` command will not consider the deleted/removed rows in status and will report incorrect imported rows count. 

The possible fix can be to use the custom file reader as in this PR: https://github.com/yugabyte/yb-voyager/pull/224

**Comment by kneeraj** [comment]
I think we can document this and defer this for future. @amit-yb ?

**Comment by hbhanawat** [comment]
@makalaaneesh @priyanshi-yb Is this relevant any more?

**Comment by makalaaneesh** [comment]
I believe it's still an issue. But not sure if we need to do anything about it. Even previously, it looks like the decision was to simply document this behavior. 

We can re-visit this again when we pick up the IDEA of handling/dealing with bad data. cc: @priyanshi-yb

**Comment by priyanshi-yb** [comment]
Yes its an issue today as well but we have documented this behavior as well [here in this note](https://docs.yugabyte.com/preview/yugabyte-voyager/migrate/migrate-steps/#import-data:~:text=In%20this%20scenario%2C%20import%20data%20status%20command%20reports%20incorrect%20imported%20row%20count%3B%20because%20it%20doesn%27t%20take%20into%20account%20the%20deleted%20rows.).

**Comment by makalaaneesh** [comment]
Thanks @priyanshi-yb , closing this then
