### ISSUE TITLE
Review analyze-schema for gaps in potential issues

### ISSUE THREAD

**Issue by rahulb-yb** [yugabyte/yb-voyager#367]
There are cases where a customer has mentioned analyze-schema gives no errors in the dumped DDL for the export schema phase, yet face issues during import schema. A review of the gaps in the breadth of analyze-schema is needed.

**Comment by priyanshi-yb** [comment]
These kind of errors are noticed which are not covered by the analyze-schema - 
```
ERROR: INDEX on column of type 'user_defined_type' not yet supported (SQLSTATE 0A000) 
ERROR: INDEX on column of type 'TEXTARRAY' not yet supported (SQLSTATE 0A000)
```
 
So, these are the cases where index creation is not supported on some data types by YugabyteDB. Also, not only index creation this can happen on any DDL which contains some thing on a column of such data type which is not supported which is basically a case where involvement of table, its columns and types are there.

**Comment by priyanshi-yb** [comment]
There are few other cases which can be added to analyze-schema such as- 

1. List Partition with multiple column  is not supported.

Example in Oracle-
```
CREATE TABLE t1 (
  id               NUMBER,
  country_code     VARCHAR2(3),
  record_type      VARCHAR2(5),
  descriptions     VARCHAR2(50),
  CONSTRAINT t1_pk PRIMARY KEY (id)
)
PARTITION BY LIST (country_code, record_type)
(
  PARTITION part_gbr_abc VALUES (('GBR','A'), ('GBR','B'), ('GBR','C')),
  PARTITION part_ire_ab  VALUES (('IRE','A'), ('IRE','B')),
  PARTITION part_usa_a   VALUES (('USA','A')),
  PARTITION part_others  VALUES (DEFAULT)
);
```
Exported DDL-
```
CREATE TABLE t1 (
    id numeric NOT NULL,
    country_code varchar(3),
    record_type varchar(5),
    descriptions varchar(50),
    PRIMARY KEY (id)
) PARTITION BY LIST (country_code, record_type) ;
```

Error -
```
 ERROR: cannot use "list" partition strategy with more than one column (SQLSTATE 42P17)
```

2. Partition using expression can not contain Primary or UNIQUE key on the table.

Example on MySQL - 
```
CREATE TABLE Sales (    
    cust_id INT NOT NULL,    
    name VARCHAR(40),       
    store_id VARCHAR(20) NOT NULL,    
     bill_no INT NOT NULL,      
     bill_date DATE PRIMARY KEY NOT NULL,     
    amount DECIMAL(8,2) NOT NULL )   
PARTITION BY RANGE (year(bill_date))(      
     PARTITION p0 VALUES LESS THAN (2016),       
    PARTITION p1 VALUES LESS THAN (2017),      
     PARTITION p2 VALUES LESS THAN (2018),       
    PARTITION p3 VALUES LESS THAN (2020)
 ); 
```

Exported DDL -
```
CREATE TABLE sales (
         	 cust_id bigint NOT NULL,
         	 name varchar(40),
 	  	 store_id varchar(20) NOT NULL,
	   	 bill_no bigint NOT NULL,
 	   	bill_date timestamp NOT NULL,
 	   	amount decimal(8,2) NOT NULL,
 	  	 PRIMARY KEY (bill_date)
) PARTITION BY RANGE (extract(year from date(bill_date))) ;
```

Error-
```
ERROR: unsupported PRIMARY KEY constraint with partition key definition (SQLSTATE 0A000) 
DETAIL:  PRIMARY KEY constraints cannot be used when partition keys include expressions.
```
or 
```
ERROR:  unsupported UNIQUE constraint with partition key definition
DETAIL:  UNIQUE constraints cannot be used when partition keys include expressions.

```

**Comment by priyanshi-yb** [comment]
Gaps identified for analyze-schema - 

1. Cases where some object type is created on some a column whose type is not supported for that object type which is not possible to add in anaylze-schema with current code. For ex- 
```
ERROR: INDEX on column of type 'user_defined_type' not yet supported (SQLSTATE 0A000) 
ERROR: INDEX on column of type 'TEXTARRAY' not yet supported (SQLSTATE 0A000)
```
2. These two are added in the analyze-schema in this PR #700 
  a. List Partition with multiple column is not supported.
  b. Partition using expression can not contain Primary or UNIQUE key on the table.
