### ISSUE TITLE
[YB-CLI] The boundary of the table list with data exported is not consistent with increasing lengths of the table names

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#368]
![Image](https://user-images.githubusercontent.com/100332069/192971053-620f0d50-9158-4df0-be55-d3d9c1210710.png)

**Same issue while checking the import status**

![Image](https://user-images.githubusercontent.com/100332069/192971973-ce74da97-822b-4622-8cf4-80f299bf1ac1.png)

**Comment by kneeraj** [comment]
Should be a small fix. Let's do it for GA 1.0
