### ISSUE TITLE
[Enhancement] Making Analyze-schema smart to report info about table partitioning

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#374]
Jira Link: [DB-13503](https://yugabyte.atlassian.net/browse/DB-13503)
Rightnow we don't have information with respect to table partitions but just tables, even partitions are considered under normal tables.
Something like which has tables has how many, what partitioning type etc could be more useful.

**Comment by hbhanawat** [comment]
Older issue. Should not be relevant anymore.
