### ISSUE TITLE
Document about some characters in the Password for the --target-db-password flag to be escaped by users

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#377]
Document about the `$` and `!` in the password string for the `--target-db-password`  which are required to be escaped with `\` in the password string itself. For e.g 
1. Test$123 - `--target-db-password "Test\$123"`
2. Test!123 - `--target-db-password "Test\!123"`

**Comment by priyanshi-yb** [comment]
https://github.com/yugabyte/yb-voyager/pull/518 Removes documenting the escaping the passwords. 
Now, we need to just document this note for `--source-db-password / --target-db-password`

> Note: Pass the password string for  `--source-db-password / --target-db-password` in single quotes, if it contains special characters.

CC: @aishwarya24

**Comment by aishwarya24** [comment]
Included it in this PR : https://github.com/yugabyte/yugabyte-db/pull/15527
