### ISSUE TITLE
Verify/Explore an appropriate order to import object types for the different source db types

### ISSUE THREAD

**Issue by rahulb-yb** [yugabyte/yb-voyager#380]
The order in which yb-voyager imports object types does not consider the possibility of dependencies (for eg. table definition being dependent on function definitions in PG). We need to explore a good order to import the various object types so as to avoid DDLs cascading in failure due to dependencies, as much as possible

**Comment by amit-yb** [comment]
Duplicate of https://github.com/yugabyte/yb-voyager/issues/410
