### ISSUE TITLE
Allow migrating blob/clob when it is known that the column size is relatively small

### ISSUE THREAD

**Issue by amit-yb** [yugabyte/yb-voyager#385]
Jira Link: [DB-13508](https://yugabyte.atlassian.net/browse/DB-13508)

**Comment by amit-yb** [comment]
@rahulb-yb Please update this ticket with whatever decision we took about blob/clob support.

**Comment by rahulb-yb** [comment]
For the documentation:
BLOBs and CLOBs are not native data types in PG- they are closest represented by the native bytea and text datatypes respectively. 
While BLOBs and CLOBs have better support for storage of data, bytea and text only allow upto 1 GB of data per cell, meaning that if the data rows we attempt to import contain >1GB of data, it would fail

As an alternative, PG provides support for LOB which are capable of holding BLOB/CLOB datatypes. This, however, is not yet supported in YB, making this alternative infeasible.

Finally, BLOB and CLOB data types can contain a lot of more data per cell as compared to most other native data types, which can cause timeout errors when combined with our logic for parallelism of import data- the size can potentially be greater by an order of upto 2^25 compared to most other data types, making it infeasible to attempt to migrate it alongside the rest of the data. Our current build already ignores importing the BLOB and CLOB _data_, but keeps the schema preserved, allowing the user to import their data onto the preserved schema by any means they wish

**Comment by shubham-yb** [comment]
From a recent experiment it was observed that CLOB datatype row values are migrated but the upper limit of the datafile was seen to be **243 MB**. 
Any greater than that and the migration errors out.
Further details are in this [sheet](https://docs.google.com/spreadsheets/d/128llu5zXnCYMNlAIfFsg4UA5eu5JhFwtcQJHNSh5EEI/edit?usp=sharing)

**Comment by hbhanawat** [comment]
Closing it based on @shubham-yb 's comments
