### ISSUE TITLE
Function truncated the code at '--' comment of SQL with BEGIN section of the function, so soon is seen the comment line in the code it just ends there.

### ISSUE THREAD

**Issue by jcpkanuri** [yugabyte/yb-voyager#395]
Function truncated the code at '--' comment of SQL with BEGIN section of the function, so soon is seen the comment line in the code it just ends there.

   For Example:

  CREATE FUNCTION xxx.xxx

  ….

    BEGIN

      Select * from dummy

Where c1 = 123

--adding comment to sql

And c2 = ‘abce

;

End

Customer had to manually remove the comment and execute the functions. Could we review this and resolve this at the earliest?

**Comment by sanyamsinghal** [comment]
@jcpkanuri please try it, it should be fixed now. Reopen if it still exists.
