### ISSUE TITLE
[MYSQL] Table and Column level COMMENTS are not migrated

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#415]
If you add some comments to a particular column or to the table on the source, it does not show up on the target.

**This is the schema I used:**

```
create table comments_check (
	id int primary key auto_increment comment 'this is the id',
	first_name VARCHAR(50) comment 'this is the first name',
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
)comment 'comment for the table';

```

**While checking on the source:**

![Image](https://user-images.githubusercontent.com/65844208/194523199-00f2b32b-ee51-4955-b2b5-11b126cf9e86.png)

**While checking on the target:**

![Image](https://user-images.githubusercontent.com/65844208/194523490-f831eb0f-b81b-4edc-9837-4df8f30927f1.png)

**Comment by rahulb-yb** [comment]
@shubham-yb can you delete your `base-ora2pg.conf` file and try again with main branch build? You will find this file in the `/etc/yb-voyager/` directory

**Comment by shubham-yb** [comment]
Worked now @rahulb-yb Thanks.
But I believe we were supposed to test it on ` 0.81-dev`?

**Comment by rahulb-yb** [comment]
You can try once again with `0.81-dev`; this was branched off of main recently. The patch which was added to fix this was introduced in main a long time back, you should get the same results

**Comment by shubham-yb** [comment]
Worked! Closing it now.
