### ISSUE TITLE
Support for Quoted Schema names

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#422]
This ticket will track the support for Quoted Schema names.

**Comment by shubham-yb** [comment]
This refers to schema names which are case sensitive on the source and thus passed with quotes while running the commands. This is not supported yet. 
As a workaround, the user may alter the name to be insensitive, run the migration and then alter the schema name according to their preference.

**Comment by priyanshi-yb** [comment]
@aishwarya24  It is there in manual review guideline for this and ready to be added in known issue page.

**Comment by aishwarya24** [comment]
Included it in this PR : https://github.com/yugabyte/yugabyte-db/pull/15527
