### ISSUE TITLE
Import of stored procedures with inline comments fails

### ISSUE THREAD

**Issue by jason-yb** [yugabyte/yb-voyager#424]
I have come across an issue with oracle migration and stored procedures.

If the source stored procedure definition includes inline comments (using —) then voyager errors when creating the procedure, if the comment has been added using block comments (using /* */) then the procedure creates without error.

If you lift the code from procedure.sql you can create the procedure even with the inline comments, so seems to be the interpretation of the procedure.sql file that is impacted when it has inline comments.

(using voyager v0.8)

log file shows
```
2022-10-10 16:01:08 ERROR importSchemaYugabyteDB.go:99 Previous SQL statement failed with error: ERROR: unexpected end of function definition at end of input (SQLSTATE 42601)
```

Examples: This will work:
```
CREATE OR REPLACE PROCEDURE ship_order (id integer) AS $body$
BEGIN
UPDATE
    orders
    /* block test, this works*/
SET
    shipped_date = CURRENT_DATE
WHERE
    order_id = id;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE ship_order (id integer) FROM PUBLIC;
```

Examples: This will fail:
```
CREATE OR REPLACE PROCEDURE ship_order1 (id integer) AS $body$
BEGIN
UPDATE
    orders
    -- inline causes errors and will fail
SET
    shipped_date = CURRENT_DATE
WHERE
    order_id = id;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE ship_order1 (id integer) FROM PUBLIC;
```

**Comment by sanyamsinghal** [comment]
@jason-yb this has been in the fix latest main branch in this PR https://github.com/yugabyte/yb-voyager/pull/480. Closing this ticket, please try again and reopen if still faces any issue.
