### ISSUE TITLE
[POSTGRES] Does not respect the --target-db-schema flag

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#434]
When we migrate from postgres the value of --target-db-schema gets ignored and the migration goes through in the public schema itself.

**Comment by amit-yb** [comment]
@shubham-yb This is an expected behaviour.
```
[amit.jambure@dev-server-ajambure yb-voyager]$ ./yb-voyager import data --help | grep target-db-schema
      --target-db-schema string       target schema name in YugabyteDB (Note: works only for source as Oracle and MySQL, in case of PostgreSQL you can ALTER schema name post import) (default "public")
```
Given that one can export multiple schemas for PG, the singular --target-db-schema doesn't help.
