### ISSUE TITLE
[Oracle/MySQL] Upgrade the conf file used for export schema/data

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#437]
The conf file we are using is quite old and has never been updated. 
There have been changes/additions in the underlying export tool after that and the conf needs to be updated.

If possible, also review all the existing properties and check if they can be changed for better behavior of `yb-voyager`.

Steps:
1. Install the latest ora2pg on your machine.
2. Create a new project using ora2pg which will generate a new conf file in it.
```
ora2pg --project_base . --init_project test_project
ls test_project/config/ora2pg.conf
```
3. Compare the already existing properties in the current conf file and check if there is any change in the default of the current conf file and new conf file
4. Replace the current file with a new one.

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore.
