### ISSUE TITLE
[MySQL] Add Automation test for Partitioned Tables

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#451]

**Comment by kneeraj** [comment]
Hi @shubham-yb and @sanyamsinghal why are we still blocked here?

**Comment by shubham-yb** [comment]
Hi, @kneeraj Wanted sub-partitions to go in with partitions so we were waiting for a while and then with Darold's fix for sub partitions, empty partitions also broke. Will work on adding it without the sub-partitions for now.

**Comment by shubham-yb** [comment]
Automation with Validations added.
