### ISSUE TITLE
[MYSQL] Table names which are reserved words in pg not migrating

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#452]
Jira Link: [DB-13511](https://yugabyte.atlassian.net/browse/DB-13511)
If we have a table name which is a reserved name in pg, the migration fails during `import data`.

This is the schema I used:

```
create table any(id int primary key auto_increment, ASYMMETRIC varchar(20), DEFERRABLE varchar(20));

insert into any(ASYMMETRIC,DEFERRABLE) values('Modestine', 'MacMeeking');
insert into any(ASYMMETRIC,DEFERRABLE) values('Genna', 'Kaysor');
insert into any(ASYMMETRIC,DEFERRABLE) values('Tess', 'Wesker');
```

This is the exported schema:

```
CREATE TABLE "any" (
	id numeric(10) NOT NULL,
	"asymmetric" varchar(20),
	"deferrable" varchar(20),
	PRIMARY KEY (id)
) ;
```

During `import data` the error is:

`failed to check whether table "any" empty: ERROR: syntax error at or near "any" (SQLSTATE 42601)`

**Comment by hbhanawat** [comment]
@shubham-yb is this issue still relevant?
