### ISSUE TITLE
[Oracle/MySQL] Verify whether exported schema has column level collations

### ISSUE THREAD

**Issue by amit-yb** [yugabyte/yb-voyager#464]
- Create a table in Oracle and MySQL such that non-default collation is attached to any character sequence type.
- Export schema of the database using voyager.
- Check if table schemas dumped in the tables.sql file has same collation info for the column.
- If collation info gets dumped in the schema:
    Document: For Oracle/MySQL collations must be fixed in the manual review phase.
- else:
    Document: Limitation: For Oracle and MySQL, voyager does not output collation info.

**Comment by shubham-yb** [comment]
For Oracle and MySQL the collation information is not exported.

**Comment by amit-yb** [comment]
Fixes https://github.com/yugabyte/yb-voyager/issues/411
