### ISSUE TITLE
Add support for TABLESPACES in migration

### ISSUE THREAD

**Issue by kneeraj** [yugabyte/yb-voyager#47]
Currently the Yugabyte migration engine cannot handle migration of tables associated with certain TABLESPACES automatically.

The workaround is to manually create the required tablespace in Yugabyte and then start the migration. Alternatively if that tablespace is not relevant in the YugabyteDB distributed cluster then the user can remove the tablespace association of the table from the create table definition.

**Comment by kneeraj** [comment]
For 1.0 GA we will add documentation as to how the user can handle this as part of manual review.

**Comment by sanyamsinghal** [comment]
closing as duplicate ticket #170 already in progress.
