### ISSUE TITLE
[import data]: determine batch state from the contents of the `ybvoyager.batches` table

### ISSUE THREAD

**Issue by amit-yb** [yugabyte/yb-voyager#472]
Jira Link: [DB-13516](https://yugabyte.atlassian.net/browse/DB-13516)
voyager import data code path uses file-name extensions (`.C`, `.P`, and `.D`) to determine state of a batch. This can be simplified by deriving the state of a batch from the contents of the `ybvoyager.batches` table.

**Comment by hbhanawat** [comment]
Clising it based on the previous comments.
