### ISSUE TITLE
--Has-Header flag not honoured while importing data from a data file

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#481]
**Description :** When a user imports data from a csv file and the file has headers then the value of --has-header is not taken into consideration during the data  import.

**Schema used**
```
drop table csv_file_test;
CREATE TABLE csv_file_test
    ( 
      id_seq NUMBER GENERATED ALWAYS AS IDENTITY
    , Industry_Year    NUMBER
    , Industry_Aggregation_Level     VARCHAR2(200)
    , Industry_Code VARCHAR2(40)
    , Industry_Type VARCHAR2(500)
    , Dollar_Percentage VARCHAR2(100)
    , Industry_name  VARCHAR2(300)
    , Variable_category VARCHAR2(100)
    , Industry_Valuation NUMBER
    , Industry_Class VARCHAR2(500)
    ) ;
ALTER TABLE csv_file_test ADD (CONSTRAINT ID_PK PRIMARY KEY (id_seq)) ;
```

**Data file used** : https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-csv.csv

**Import command used**
```
yb-voyager import data file --export-dir ${EXPORT_DIR} \
        --target-db-host ${TARGET_DB_HOST} \
        --target-db-user ${TARGET_DB_USER} \
        --target-db-password ${TARGET_DB_PASSWORD} \
        --target-db-name ${TARGET_DB_NAME} \
        --data-dir "/home/ubuntu/data_files" \
        --file-table-map "annual-enterprise-survey-2021-financial-year-provisional-csv.csv:csv_file_test" \
        --delimiter "," \
        --format csv \
        –-has-header
```

**Contents of the dataFileDescriptor.json**
{
	"FileFormat": "csv",
	"TableRowCount": null,
	"TableFileSize": {
		"csv_file_test": 6617174
	},
	"Delimiter": ",",
	"HasHeader": false
}

@sanyamsinghal  **Latest Error on import data using file** 

2022-10-17 15:00:03 WARN importData.go:818 COPY FROM file "/home/ubuntu/export-dir/metainfo/data/csv_file_test.2.40000.20000.3169182.P": ERROR: extra data after last expected column (SQLSTATE 22P04)
2022-10-17 15:00:03 INFO importData.go:823 sleep for 30 seconds before retrying the file /home/ubuntu/export-dir/metainfo/data/csv_file_test.2.40000.20000.3169182.P (attempt 3)

**Comment by kneeraj** [comment]
Can we please close this now @chetank-yb

**Comment by chetank-yb** [comment]
The issue was with the schema mismatch.
Closing the issue after testing it with a newer schema.

drop table csv_file_test;
CREATE TABLE csv_file_test
    (
      id_seq NUMBER GENERATED ALWAYS AS IDENTITY 
    , Industry_Year    NUMBER
    , Industry_Aggregation_Level     VARCHAR2(200)
    , Industry_Code VARCHAR2(40)
    , Industry_Type VARCHAR2(500)
    , Dollar_Percentage VARCHAR2(100)
    , Industry_name  VARCHAR2(300)
    , Variable_Sub_Category VARCHAR2(500)
    , Variable_Category VARCHAR2(100)
    , Industry_Valuation VARCHAR2(50)
    , Industry_Class VARCHAR2(500)
    ) ;
    ALTER TABLE csv_file_test ADD (CONSTRAINT ID_PK PRIMARY KEY (id_seq));
