### ISSUE TITLE
yb-voyager install is failing on Redhat Linux distribution

### ISSUE THREAD

**Issue by jcpkanuri** [yugabyte/yb-voyager#487]
I tried to install yb-voyager on Redhat Linux distribution and encountered the error message stating that Redhat Linux is not supported.

Script failed. Check log file /tmp/install-yb-voyager.log
```
++ cat /etc/os-release
++ grep -w NAME
++ awk -F= '{print $2}'
++ tr -d '"'
+ dist='Red Hat Enterprise Linux'
+ case ${dist} in
+ echo 'ERROR: unsupported linux distribution: Red Hat Enterprise Linux'
+ exit 1
+ on_exit
+ rc=1
+ set +x
```
 
Unix Version:

```
Linux 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Mon Jul 18 11:14:02 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Is there a plan to support Redhat distribution?

Thanks
Jai Kanuri

**Comment by ShivanshGahlot** [comment]
The error was occurring because an older version of the installer script bundled along with `0.80 `release was being used. The solution is to clone from the `main` branch and use the installer script obtained from the clone.
