### ISSUE TITLE
Support migration to cluster created on YB cloud

### ISSUE THREAD

**Issue by kneeraj** [yugabyte/yb-voyager#52]
Currently the migration engine needs super user privileges on the destination YB cluster. This is not possible in the cluster created through YB cloud. We are working to reduce those privileges for cloud. This is under active development and should be available soon.

**Comment by sanyamsinghal** [comment]
Currently cloud is on `2.12.5` which has all the fixes related except `REASSIGN` user permission which will be available starting `2.12.6`
