### ISSUE TITLE
import schema fails in the presence of a multi-line COMMENT containing a semi-colon

### ISSUE THREAD

**Issue by amit-yb** [yugabyte/yb-voyager#520]
Create a comment that has multiple lines and a semi-colon:
```
dvdrental=# comment on table store is E'line1;
line2';
COMMENT
```
The exported schema in the `comment.sql` looks like:
```
COMMENT ON TABLE public.store IS 'line1;
line2';
```
In this case, voyager tries to apply `COMMENT ON TABLE public.store IS 'line1;` part as a single statement which fails with unterminated string error.

**Comment by sanyamsinghal** [comment]
Workaround has been introduced as part of this PR https://github.com/yugabyte/yb-voyager/pull/536

**Comment by sanyamsinghal** [comment]
The final fix will be covered in this ticket - https://github.com/yugabyte/yb-voyager/issues/537

**Comment by chetank-yb** [comment]
This ticket will be validated once the fix is pushed by @sanyamsinghal. For now in 0.81 exporting comments have been disabled.
