### ISSUE TITLE
Could not import trigger with import schema for latest build

### ISSUE THREAD

**Issue by tichimura** [yugabyte/yb-voyager#527]
Problem: 
- Could not import trigger with option `--object-list TRIGGER`

Background:

- Env:
  - local build on Mac OS with ` ./install-yb-voyager -l`

  ```
  % yb-voyager version
  VERSION=main
  GIT_COMMIT_HASH=83a101123e0ecd7dd939f60adfdba0fb5705ea3e
  LAST_COMMIT_DATE=2022-10-31T06:36:35Z
  ```

- What happened

  ```
  % yb-voyager import schema --object-list TRIGGER --continue-on-error --export-dir ${EXPORT_DIR} \
  --target-db-host ${TARGET_DB_HOST} \
  --target-db-name ${TARGET_DB_NAME} \
  --target-db-user ${TARGET_DB_USER} \
  --target-db-password ${TARGET_DB_PASSWORD} --ignore-exist
  YugabyteDB version: 11.2-YB-2.15.2.0-b0
  schemas to be present in target database "voyager": [public]
  schema 'public' already present in target database, continuing with it..
  
  Importing "/Users/tichimura/Downloads/20221026_YB/schema/schemas/schema.sql"
  
  CREATE SCHEMA public;
  
  tichimura@ yb-voyager-oct31 %
  ```
  
 triggers.sql is not imported with this operation, we can see the file is there.
  
  ```
  tichimura@ yb-voyager-oct31 % ls /Users/tichimura/Downloads/20221026_YB/schema/triggers/
  trigger.sql
  ```
  
 Expectations:
 - `--object-list TRIGGER ` can handle the importing of triggers.
 
 @sanyamsinghal

**Comment by sanyamsinghal** [comment]
I am assuming you are using the latest main branch.
Now, Triggers are migrated during the `--post-import-data` phase with this new flag in the `import schema` command. Here you are running the `import schema` command without this flag so anyways they are skipped/deferred to the postImportData phase. 
PostImportData phase imports TRIGGER and INDEX
This is a change in the workflow which has been done in the main branch. It soon will be updated in docs etc before the next 0.81 near this weekend.
