### ISSUE TITLE
[Enhancement] SQL parsing during import schema to check the starting keywords with possible ones

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#537]
Jira Link: [DB-13474](https://yugabyte.atlassian.net/browse/DB-13474)
Parser should check the start of every SQL statement to be one of the allowed keywords like `CREATE` `ALTER` `SET` `DROP` `TRUNCATE` etc

**Comment by sanyamsinghal** [comment]
Example of Failing DDLs:
```
comment on table store is E'line1;
line2';
```

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore.
