### ISSUE TITLE
[PostgreSQL] Partition data is not imported

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#538]
While migrating partitions from postgres, the `import-data` completes without populating any data in the partitions on the target. This was observed for all kinds of partitions.

Source schema:

```
drop table if exists list_part;

CREATE TABLE list_part (id INTEGER, status TEXT, arr NUMERIC) PARTITION BY LIST(status);

CREATE TABLE list_active PARTITION OF list_part FOR VALUES IN ('ACTIVE');

CREATE TABLE list_archived PARTITION OF list_part FOR VALUES IN ('EXPIRED');

CREATE TABLE list_others PARTITION OF list_part DEFAULT;

INSERT INTO list_part VALUES (1,'ACTIVE',100), (2,'RECURRING',20), (3,'EXPIRED',38), (4,'REACTIVATED',144), (5,'ACTIVE',50);

\d+ list_part


```

The import data shows that the partitions aren't being populated.

![Image](https://user-images.githubusercontent.com/65844208/199677955-7fdec255-253a-4c3c-8b0d-b2338052e03d.png)

Query to check the partition rows:

```
SELECT tableoid::regclass,* FROM list_part;
```

Source output:

![Image](https://user-images.githubusercontent.com/65844208/199678221-42ec4f53-5a5e-44d1-b3f2-f0a8f2a14ac1.png)

Target output:

![Image](https://user-images.githubusercontent.com/65844208/199678311-727427ef-ee63-4314-9ec5-bf13898030a2.png)

**Comment by sanyamsinghal** [comment]
This will be fixed as a part of this ticket - https://github.com/yugabyte/yb-voyager/issues/540
Closing this one
