### ISSUE TITLE
[PostgresSQL] Superuser access required to access some system objects

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#541]
In Postgres when we provide the grants to the `ybvoyager` user, the permissions for some system objects ex: `pg_catalog` are not granted if the user is not a `superuser`. This was observed in AWS RDS instances as it only provides the `superuser` role to 
` rdsadmin`, and some of the grants were failing, thus hindering some specific exports as well.

**Grants failing:**

1. `GRANT USAGE ON SCHEMA pg_catalog TO ybvoyager;`
 
Fails with:

`WARNING:  no privileges were granted for "pg_catalog"`

2.  `GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO ybvoyager;`

Fails with:

`ERROR:  permission denied for table pg_statistic`

Due to this, the extension for `pg_catalog` does not export. (One that we know for now)

**Source extensions:**

![Image](https://user-images.githubusercontent.com/65844208/199754056-71012dd7-5099-4332-a767-5df45237bd23.png)

**Exported extensions:**

![Image](https://user-images.githubusercontent.com/65844208/199754383-f66980b5-ae26-4397-8edb-2d7f9a8f45d0.png)

**Comment by sanyamsinghal** [comment]
1. Verify complete migration using voyager
2. Research about what all pg_catalog schema tables GRANT is not given.

**Comment by rahulb-yb** [comment]
I used a more incremental query to view which tables do not get the required permissions:
`grant select on ' || table_schema || '.' || table_name || ' to ybvoyager;' from information_schema.tables;`
There are additional tables for which errors like:
```WARNING:  no privileges were granted for "pg_stat_progress_analyze"``` or ```ERROR:  permission denied for table pg_subscription``` show up, however these do not interrupt the flow of the migration.
The extension specified in the issue description is available by default on YB, so it is not something we should be concerned about either

**Comment by amit-yb** [comment]
In short: the warning should not have any effect on the migration.

To verify the issue, I created a new user `ybvoyager3` on an RDS PG instance.
```
[amit.jambure@dev-server-ajambure ~]$ psql -h ssinghal-dms-postgres.cbtcvpszcgdq.us-west-2.rds.amazonaws.com -U postgres
Password for user postgres:
psql (14.5, server 11.16)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=> CREATE USER ybvoyager3 PASSWORD 'password';
CREATE ROLE
postgres=> \c dvd
psql (14.5, server 11.16)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
You are now connected to database "dvd" as user "postgres".
```
Then I created an SQL script to count rows from each table from the `pg_catalog` schema--without assigning ANY privilege to the newly created user.
```
[amit.jambure@dev-server-ajambure ~]$ head count_rows_in_each_catalog_table.sql
SELECT count(*) FROM pg_catalog.pg_aggregate;
SELECT count(*) FROM pg_catalog.pg_am;
SELECT count(*) FROM pg_catalog.pg_amop;
SELECT count(*) FROM pg_catalog.pg_amproc;
SELECT count(*) FROM pg_catalog.pg_attrdef;
SELECT count(*) FROM pg_catalog.pg_attribute;
SELECT count(*) FROM pg_catalog.pg_auth_members;
SELECT count(*) FROM pg_catalog.pg_authid;
SELECT count(*) FROM pg_catalog.pg_cast;
SELECT count(*) FROM pg_catalog.pg_class;
[amit.jambure@dev-server-ajambure ~]$ wc -l count_rows_in_each_catalog_table.sql
62 count_rows_in_each_catalog_table.sql
```
Among the 62 SELECT queries, only four fail with the permission denied issue:
```
[amit.jambure@dev-server-ajambure ~]$ psql -h ssinghal-dms-postgres.cbtcvpszcgdq.us-west-2.rds.amazonaws.com -U ybvoyager3 -d postgres -c '\i count_rows_in_each_catalog_table.sql' | grep permission
Password for user ybvoyager3:
psql:count_rows_in_each_catalog_table.sql:8: ERROR:  permission denied for table pg_authid
psql:count_rows_in_each_catalog_table.sql:29: ERROR:  permission denied for table pg_largeobject
psql:count_rows_in_each_catalog_table.sql:49: ERROR:  permission denied for table pg_statistic
psql:count_rows_in_each_catalog_table.sql:62: ERROR:  permission denied for table pg_user_mapping
```
Similar result is observed, when I repeated the same experiment with Postgres running on my local machine:
```
[amit.jambure@dev-server-ajambure ~]$ psql -U ybmigrate -d postgres -c '\i count_rows_in_each_catalog_table.sql' | grep permission
Password for user ybmigrate:
psql:count_rows_in_each_catalog_table.sql:8: ERROR:  permission denied for table pg_authid
psql:count_rows_in_each_catalog_table.sql:29: ERROR:  permission denied for table pg_largeobject
psql:count_rows_in_each_catalog_table.sql:36: ERROR:  relation "pg_catalog.pg_pltemplate" does not exist
LINE 1: SELECT count(*) FROM pg_catalog.pg_pltemplate;
                             ^
psql:count_rows_in_each_catalog_table.sql:49: ERROR:  permission denied for table pg_statistic
psql:count_rows_in_each_catalog_table.sql:62: ERROR:  permission denied for table pg_user_mapping
```
