### ISSUE TITLE
Import data 'Error Resolving name' on local kubernetes

### ISSUE THREAD

**Issue by aphawkins** [yugabyte/yb-voyager#553]
Following the YugabyteDB Voyager database migration steps (https://docs.yugabyte.com/preview/migrate/migrate-steps/) going from PostgreSQL to YugabyteDB on a local Kubernetes, on Docker Desktop, on WSL2, on Windows. Using Ubuntu 22.04 on WSL2 to run yb-voyager.
The command used to import the data, which fails:
```
yb-voyager import data --export-dir ${EXPORT_DIR} --target-db-host ${TARGET_DB_HOST} --target-db-user ${TARGET_DB_USER} --target-db-password ${TARGET_DB_PASSWORD} --target-db-name ${TARGET_DB_NAME}
```
The error message on the Import Data step:
```
import of data in "postgres" database started
Target YugabyteDB version: 11.2-YB-2.15.2.1-b0
Error Resolving name=yb-tserver-1.yb-tservers.yb-demo.svc.cluster.local: lookup yb-tserver-1.yb-tservers.yb-demo.svc.cluster.local: no such host
```
The Import Schema step worked correctly (from using pgAdmin connected to the YugabyteDB), so I know that the database can be connected to. Command used:
```
yb-voyager import schema --export-dir ${EXPORT_DIR} --target-db-host ${TARGET_DB_HOST} --target-db-user ${TARGET_DB_USER} --target-db-password ${TARGET_DB_PASSWORD} --target-db-name ${TARGET_DB_NAME}
```

env variables:
```
EXPORT_DIR=/home/abc/db-export
TARGET_DB_HOST=127.0.0.1
TARGET_DB_USER=ybvoyager
TARGET_DB_PASSWORD=password
TARGET_DB_NAME=postgres
```
Pod list:
```
kubectl get pods -n yb-demo
NAME           READY   STATUS    RESTARTS      AGE
yb-master-0    2/2     Running   2 (96m ago)   3d18h
yb-master-1    2/2     Running   2 (96m ago)   3d18h
yb-master-2    2/2     Running   2 (96m ago)   3d18h
yb-tserver-0   2/2     Running   2 (96m ago)   3d18h
yb-tserver-1   2/2     Running   2 (96m ago)   3d18h
yb-tserver-2   2/2     Running   2 (96m ago)   3d18h
```

**Comment by mheer9** [comment]
Hi @aphawkins 
Are you running yb-voyager within the tserver-1 pod ?
As seen you have specified TARGET_DB_HOST=127.0.0.1

Can you share the output from
kubectl get pods -n yb-demo -o wide

**Comment by sanyamsinghal** [comment]
Hi, @aphawkins can you share more details to analyze it better:
1. yb-voyager.log file
2. import Schema and import data command with the actual value of variables like ${TARGET_DB_HOST}, ${TARGET_DB_NAME}
3. Just to confirm: Is `yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local` reachable from the machine where you are running yb-voyager


So during the import data, internally in code we use the output of `yb_servers()` function query and take the servers and compare them with the given `--target-db-host` flag to determine whether the given flag is a load balancer IP or one of the cluster's server.
So currently it is expected that at least all the hostname DNS will be resolvable(if not reachable) from the yb-voyager machine to do the above comparison, even if it is not reachable it should be resolvable to an IP.

Workarounds:
1. All the servers' hostnames should be reachable/resolvable from the yb-voyager machine.
2. Use `--target-endpoints` flag(which will override `yb_servers()` output) to just provide the servers which are resolvable/reachable from voyager client machine.

**Comment by aphawkins** [comment]
1. Log file attached [yb-voyager.log](https://github.com/yugabyte/yb-voyager/files/9981107/yb-voyager.log)
2. Command used: `yb-voyager import data --export-dir /home/andy/db-export --target-db-host 127.0.0.1 --target-db-user ybvoyager --target-db-password password --target-db-name postgres`
3. That servers are not reachable from the machine.  YugabyteDB is being run in kubernetes, while yb-voyager is being run in Ubuntu.  The LoadBalancer exposes `yb-tserver-service` on `localhost:5433`, which is reachable from Ubuntu.

`yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local` will only be resolvable from within the kubernetes cluster, so am I right to assume that in order to use yb-voyager on a kubernetes deployed YugabyteDB, then voyager must also be run from within kubernetes?

**Comment by sanyamsinghal** [comment]
Hi @aphawkins thanks for the details.
Ideally, yb-voyager `import data` should work if there is a LB between voyager and cluster and LB is reachable from voyager.  And should not fail trying resolving the hosts in that case. I have filed a ticket for thjis bug - https://github.com/yugabyte/yb-voyager/issues/585

In the meantime can you please trying the workaround #2 suggested above, using `--target-endpoints=127.0.0.1:5433` for import data command.

**Comment by sanyamsinghal** [comment]
closing this for now as it is now tracked in - https://github.com/yugabyte/yb-voyager/issues/585
