### ISSUE TITLE
[ORACLE] For Datatype validation, validate mapping as well

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#555]
Jira Link: [DB-13484](https://yugabyte.atlassian.net/browse/DB-13484)
In our validations, we also need to check if the mapping for a corresponding datatype is as expected.

**Comment by chetank-yb** [comment]
Hello, 
The testing for this ticket was done with main (pre-commit with fixes) & in revert-309-rahul-oracle-number (branch with the fixes).
It was observed that the mapping from **oracle to postgres** was same in both the cases as shown below, 

1. FLOAT(5) -> double precision
2. BINARY_FLOAT -> double precision
3. BINARY_DOUBLE -> double precision
4. DATE -> timestamp
5. TIMESTAMP(9) -> timestamp
6. TIMESTAMP WITH TIME ZONE -> timestamp with time zone
7. TIMESTAMP WITH LOCAL TIME ZONE -> timestamp with time zone
8. INTERVAL YEAR(4) TO MONTH -> INTERVAL YEAR TO MONTH
9. INTERVAL DAY(9) TO SECOND(9) -> INTERVAL DAY TO SECOND(6)
10. VARCHAR2 -> varchar
11. NVARCHAR2 -> varchar
12. CHAR -> char
13. NCHAR -> CHAR
14. LONG -> text
15. RAW -> bytea
16. LONG RAW -> bytea
17. NUMBER -> NUMERIC
18. NUMBER(3) -> NUMERIC(3)
19. NUMBER(3,2) -> REAL
20. NUMBER(2,7) -> NUMERIC
21. NUMBER(6,-2) -> REAL

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore. We have the test coverage available separately.
