### ISSUE TITLE
[Docs] Mapping of datatypes from MySQL to YugabyteDB

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#559]
In docs, there should be a table showing the mapping of corresponding datatypes in MySQL to what in YugabyteDB

**Comment by shubham-yb** [comment]
Created a doc for the same.

https://docs.google.com/spreadsheets/d/1rg-4V3BnsWY0ptJWrdvr4HDQDbIUMgLksUOtr342odw/edit#gid=0

**Comment by shubham-yb** [comment]
I've completed the sheet with the mappings.
Do we close this ticket or wait for it to go in our official docs?
