### ISSUE TITLE
[Docs] Mapping of datatypes from Oracle to YugabyteDB

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#560]
In docs, there should be a table showing the mapping of corresponding datatypes in Oracle to what in YugabyteDB

**Comment by shubham-yb** [comment]
Use this sheet for the updates

https://docs.google.com/spreadsheets/d/1rg-4V3BnsWY0ptJWrdvr4HDQDbIUMgLksUOtr342odw/edit#gid=2082822017

**Comment by chetank-yb** [comment]
Updated the sheet with all the latest test details. Closing the ticket.
