### ISSUE TITLE
Missing Primary key  is not reported in the assessment report

### ISSUE THREAD

**Issue by jamesydb** [yugabyte/yb-voyager#563]
Hi Team,
Can you please add the support to report the missing the primary key in the assessment report.

Thanks
Jaimin

**Comment by kneeraj** [comment]
Hi @jamesydb , can you please elaborate on this bug. Like source-db, schema you are using. When do you notice this is missing. And missing from where, like the exported ddls or in the. finally migrated table in YB.

**Comment by kneeraj** [comment]
Not enough information. Not actionable. @jamesydb I am closing this for now. If you have more information on this please file a new one or reopen this with specific asks.
