### ISSUE TITLE
PG13: unrecognized configuration parameter "default_table_access_method" (SQLSTATE 42704)

### ISSUE THREAD

**Issue by amit-yb** [yugabyte/yb-voyager#60]
While migrating a DB from Postgres 13.6, `import schema` fails with the following error:
```
importing     SCHEMA      
    ERROR: unrecognized configuration parameter "default_table_access_method" (SQLSTATE 42704)
    STATEMENT: SET default_table_access_method = heap;
ERROR: unrecognized configuration parameter "default_table_access_method" (SQLSTATE 42704)
```
`yb_migrate` should drop the line before attempting schema import. Until yb_migrate does that users are advised to manually look for the lines in the `$EXPORT_DIR/schema/***` and delete them.

**Comment by rahulb-yb** [comment]
Added commit to resolve this issue: #128
