### ISSUE TITLE
[MYSQL] Export data hangs for sub-partitions

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#607]
When we have a sub partitioned table in mysql, the migration hangs in the `export-data` phase. Earlier it used to error out from the ora2pg side but now it goes through if we directly use it. Still hanging via voyager. Attaching a sample schema for reference.

```
CREATE TABLE subpartitioning_test (BILL_NO INT, sale_date DATE, cust_code VARCHAR(15), 
AMOUNT DECIMAL(8,2))
PARTITION BY List(MONTH(sale_date) )
SUBPARTITION BY HASH(TO_DAYS(sale_date))
SUBPARTITIONS 2 (
PARTITION p0 VALUES IN (1, 2),   
PARTITION p1 VALUES IN (3, 4),   
PARTITION p2 VALUES IN (5, 6),   
PARTITION p3 VALUES IN (7,8,9),
PARTITION p4 VALUES IN (10,11,12)
);   


INSERT INTO subpartitioning_test VALUES (1, '2013-01-02', 'C001', 125.56), 
(2, '2013-01-25', 'C003', 456.50), 
(3, '2014-02-15', 'C012', 365.00), 
(4, '2013-03-26', 'C345', 785.00), 
(5, '2013-04-19', 'C234', 656.00), 
(6, '2013-05-31', 'C743', 854.00), 
(11, '2013-05-31', 'C743', 854.00),
(7, '2013-06-11', 'C234', 542.00), 
(8, '2013-07-24', 'C003', 300.00), 
(9, '2013-08-02', 'C456', 475.20),
(10, '2013-11-02', 'C456', 475.20);


SELECT PARTITION_NAME, TABLE_ROWS FROM INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_NAME='subpartitioning_test';


```

Also I cross-checked the data files created by ora2pg and voyager and they match with just `postdata.sql` extra on our side.

Last couple of lines in the log file:

```
2022-11-21 08:29:18 INFO mysql.go:38 Querying row count of table automation.subpartitioning_test
2022-11-21 08:29:18 INFO mysql.go:43 Table "automation.subpartitioning_test" has 11 rows.
2022-11-21 08:29:18 INFO exportDataStatus.go:191 Replacing actualRowCount=11 inplace of expectedRowCount=11 for table=automation.subpartitioning_test
```

**Comment by rahulb-yb** [comment]
Progress on issue so far:
All progress has been made in the branch [rahul-mysql-subpartitions](https://github.com/yugabyte/yb-voyager/tree/rahul-mysql-subpartitions)

- Export side support has been completed for both oracle and mysql, need to verify behaviour with export data status command.
- Import side support has to be implemented in a way that doesn't depend on naming conventions prepared by the internal tool; some sort of table-file map should be created without depending on the filename for the table name directly.
- Also verify that the behaviour of the code implemented is consistent through the different versions of the internal tool being used, for the import phase of the migration. Keep in mind that the config file uses a different naming convention in future versions for partition support.
- Verify the behaviour with import data status command once import side changes have been made.
