### ISSUE TITLE
[Automation] Enable/Update the pg-partitions-with-indexes test for YB Version 2.15

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#625]
Currently, we have disabled `pg-partitions-with-indexes` to run against `2.15.3.2-b1` 
Creating this ticket to track if in future it needs to enabled or updated to run against some other build/version of YB

**Comment by shubham-yb** [comment]
The fix was pushed in DB build 2.17.1.0 b368.
