### ISSUE TITLE
[Documentation] Review the explanation of flags in docs

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#634]
Need to review the explanation of the flags in the docs whether they are appropriate and clear to the user. 
Example, `--export-dir` flag has unclear explanation on the docs ( https://docs.yugabyte.com/preview/migrate/yb-voyager-cli/#export-dir ) as it mentions - 
```
--export-dir
Specifies the path to the directory containing the data files to export.
```

which is not appropriate for the `--export-dir`. 

help message explains it better - 
```
--export-dir string   export directory to keep all the dump files and metainfo
```

**Comment by amit-yb** [comment]
Duplicated by #445 .
