### ISSUE TITLE
Enhance Export and Import Data Status commands 

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#678]
Jira Link: [DB-13488](https://yugabyte.atlassian.net/browse/DB-13488)
1. Currently in status commands we don't have information about whether the migration is still running or has stopped/failed, it just shows the status or percentage of migration for each table.
Task: Add a line at the start of the output of the `export/import data status` command whether: `NOT-STARTED`, `ONGOING`, `COMPLETED`, `FAILED`

2. Add more columns to the `export data status` command to have - `EXPORTED_ROWS`, `TOTAL_ROWS`, and `PERCENTAGE`, right now it just shows the status of whether its done, exporting, or not-started.
An extra file will be required to store the current exported row count during the export which can be read by status command.

3. Minor change: in the import status command output we use the keyword `MIGRATING` but to be uniform we should use `IMPORTING` 

4. Bug: Export Data status command for Oracle/MySQL doesn't show the status for `NOT-STARTED` tables.

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore.
