### ISSUE TITLE
Revisit all the issues detected in analyze-schema are still valid on currently supports YB versions - 2.14, 2.16 and 2.17

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#686]
Anaylze-Schema reports - ` LANGUAGE C not supported yet.` but recently when i tested it for a function on `2.17` build, it is working.

So we should revisit all the checks there to see if any other stale check is present

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore.
