### ISSUE TITLE
Provide updated user setup steps for Oracle

### ISSUE THREAD

**Issue by amit-yb** [yugabyte/yb-voyager#718]
Jira Link: [DB-13455](https://yugabyte.atlassian.net/browse/DB-13455)
Refer the comments for the list of changes required in the `Oracle` tab at https://docs.yugabyte.com/preview/migrate/migrate-steps/#prepare-the-source-database \.

**Comment by amit-yb** [comment]
Step 1:
```
```
CREATE ROLE <SCHEMA_NAME>_reader_role;
  BEGIN
    FOR R IN (SELECT owner, object_name FROM all_objects WHERE owner='<SCHEMA_NAME>' and object_type in ('VIEW','SEQUENCE','TABLE PARTITION','TABLE','SYNONYM','MATERIALIZED VIEW')) LOOP
        EXECUTE IMMEDIATE 'grant select on '||R.owner||'."'||R.object_name||'" to <SCHEMA_NAME>_reader_role';
  END LOOP;
END;
/
  BEGIN
    FOR R IN (SELECT owner, object_name FROM all_objects WHERE owner='<SCHEMA_NAME>' and object_type in ('PROCEDURE','FUNCTION','PACKAGE','PACKAGE BODY', 'TYPE')) LOOP
        EXECUTE IMMEDIATE 'grant execute on '||R.owner||'."'||R.object_name||'" to <SCHEMA_NAME>_reader_role';
  END LOOP;
END;
/
```

**Comment by amit-yb** [comment]
Create a user ybvoyager and grant CONNECT and <SCHEMA_NAME>_reader_role to the user:
```
CREATE USER ybvoyager IDENTIFIED BY password;
GRANT CONNECT TO ybvoyager;
GRANT <SCHEMA_NAME>_reader_role TO ybvoyager;
```

**Comment by amit-yb** [comment]
Completely remove the Step 3.

**Comment by aishwarya24** [comment]
Addressed this issue in PR: https://github.com/yugabyte/yugabyte-db/pull/15348

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore.
