### ISSUE TITLE
Document about the unsupported gin index cases in known issues

### ISSUE THREAD

**Issue by priyanshi-yb** [yugabyte/yb-voyager#724]
Jira Link: [DB-13458](https://yugabyte.atlassian.net/browse/DB-13458)
Issue in some of the gin index type as gin indexes are partially supported by YugabyteDB (https://github.com/yugabyte/yugabyte-db/issues/7850). 
For example, Oracle as a sourceDB: 
Multi column gin index.
Source Schema -
```
CREATE TABLE members(
    member_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR2(255) NOT NULL,
    PRIMARY KEY(member_id)
);

CREATE BITMAP INDEX members_gender_bm_index on members(gender,member_id);
```
Exported Schema - 
```
CREATE TABLE members (
	member_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	first_name varchar(100) NOT NULL,
	last_name varchar(100) NOT NULL,
	gender char(1) NOT NULL,
	dob timestamp NOT NULL,
	email varchar(255) NOT NULL,
	PRIMARY KEY (member_id)
) ;
CREATE INDEX members_gender_bm_index ON members USING gin(gender, member_id);
```
Error in import schema - 
```
ERROR: data type character has no default operator class for access method "ybgin" (SQLSTATE 42704)
```
**Workaround** is to modify such type of indexes with some supported cases or use other type of indexing as per requirement.

**Comment by priyanshi-yb** [comment]
Added this in manual review guideline docs, please update the known issues page @aishwarya24. Thanks

**Comment by aishwarya24** [comment]
Resolved in this PR : https://github.com/yugabyte/yugabyte-db/pull/15758
