### ISSUE TITLE
[docs] [migrate] Steps for Verify a migration using YB-Voyager

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/yb-voyager#728]
- We need steps to verify a migration at this section: https://docs.yugabyte.com/preview/migrate/migrate-steps/#verify-migration
and remove the current redirect :https://docs.yugabyte.com/preview/manage/data-migration/bulk-import-ysql/#verify-a-migration

- Mention this issue - https://github.com/orgs/yugabyte/projects/10/views/11?pane=issue&itemId=17443880 during the data validation

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore.
