### ISSUE TITLE
Voyager doesn't recognize Hasura's syntax for stored procedures

### ISSUE THREAD

**Issue by dmagda** [yugabyte/yb-voyager#765]
I was migrating the following eCommerce application from PostgreSQL: 
https://github.com/YugabyteDB-Samples/hasura-ecommerce

The application has a public schema with the app-specific data and `hdb_catalog` schema with Hasura metadata. The following command was used during the `schema export` step:
```shell
yb-voyager export schema --export-dir $VOYAGER_EXPORT_DIR \
    --source-db-type postgresql \
    --source-db-host 34.23.188.24 \
    --source-db-user postgres \
    --source-db-password 'password' \
    --source-db-name postgres \
    --source-db-schema 'public,hdb_catalog'
```

The tool exports the following stored procedure of Hasura to the `voyager_export_dir\schema\functions\functions.sql` file:
```sql
CREATE FUNCTION hdb_catalog.gen_hasura_uuid() RETURNS uuid
    LANGUAGE sql
    AS $$select gen_random_uuid()$$; 
```

The `analyze-schema` and `import schema` commands complete succesfully and don't report any issues. But the stored procedure above (and all the others that are defined below it) are not imported. The import fails silently.

As a workaround, the stored procedure's format needs to be changed to the following:
```sql
CREATE FUNCTION hdb_catalog.gen_hasura_uuid() RETURNS uuid
LANGUAGE sql
AS $$
        select gen_random_uuid()
$$;
```

**Comment by sanyamsinghal** [comment]
fix merged to `main`
