### ISSUE TITLE
Missing permissions for an extension that is accessed from a custom schema

### ISSUE THREAD

**Issue by dmagda** [yugabyte/yb-voyager#766]
I was migrating the following eCommerce application from PostgreSQL:
https://github.com/YugabyteDB-Samples/hasura-ecommerce

The application has a public schema with the app-specific data and `hdb_catalog` schema with Hasura metadata. The following command was used during the schema export step:
```shell
yb-voyager export schema --export-dir $VOYAGER_EXPORT_DIR \
    --source-db-type postgresql \
    --source-db-host 34.23.188.24 \
    --source-db-user postgres \
    --source-db-password 'password' \
    --source-db-name postgres \
    --source-db-schema 'public,hdb_catalog'
```

Voyager exports the following extension that is used by the application (the `public` schema) as well as Hasura (the `hdb_catalog` schema):
```sql
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
```

However, during the `schema import` step,  Voyager can't create the following stored procedure of Hasura in YugabyteDB:
```sql
CREATE FUNCTION hdb_catalog.gen_hasura_uuid() RETURNS uuid
LANGUAGE sql
AS $$
        select gen_random_uuid()
$$;
```

The logs say that the `get_random_uuid()` function (that belongs to the `pgcrypto` extension) doesn't exist. We need to set some permissions so that the `ybvoyager` user can use the extension from a custom schema like `hdb_catalog`. Plus, the `schema import` command shouldn't fail silently. I dug the issue only be looking into the logs.

**Comment by priyanshi-yb** [comment]
This function `hdb_catalog.gen_hasura_uuid()`  should be created. You can try on target database by running this query to check if function is there or not - 
```
SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'hdb_catalog';
```
it should return that function and Hence, that function is created. 

> The logs say that the get_random_uuid() function (that belongs to the pgcrypto extension) doesn't exist.

In first go it might have failed and logs must have said that. But voyager will retry in such scenarios and it will be created if everything required for that is available else it will come up in `failed.sql` where all the failed SQL statements come at the end and import schema will exit with a note for the user to review that `failed.sql`.

**Comment by dmagda** [comment]
You're referring to the old logs. This ticket describes a different problem that I came across after fixing the Hasura's function definition.

I followed your advice and changed the Hasura's function definition to the following:
```sql
CREATE FUNCTION hdb_catalog.gen_hasura_uuid() RETURNS uuid
LANGUAGE sql
AS $$
        select gen_random_uuid()
$$;
```

After importing the schema to YugabyteDB, I do see the function created:
```sql
set search_path to hdb_catalog;
yugabyte=# \df
                               List of functions
   Schema    |      Name       | Result data type | Argument data types | Type
-------------+-----------------+------------------+---------------------+------
 hdb_catalog | gen_hasura_uuid | uuid             |                     | func
(1 row)
```

But if I try to call the function from within the `hdb_catalog` schema, YugabyteDB says the following:
```sql
yugabyte=# select hdb_catalog.gen_hasura_uuid();
ERROR:  function gen_random_uuid() does not exist
LINE 2:         select gen_random_uuid()
                       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:
        select gen_random_uuid()

CONTEXT:  SQL function "gen_hasura_uuid" during inlining
```
As you see, the error says that the `gen_random_uuid()` function of the `pgcrypto` extension is not find.

But, if I switch to the `public` schema and call the Hasura's function with no issues which means `pgcrypto` is installed:
```sql
yugabyte=# set search_path to public;
SET
yugabyte=# select hdb_catalog.gen_hasura_uuid();
           gen_hasura_uuid
--------------------------------------
 28b6c14b-c1ed-4502-ab73-b1a358bfeaf7
(1 row)
```

I'm attaching the logs from this execution. Also, you can reproduce the issue by starting the app on your local laptop. Just follow this instruction: https://github.com/YugabyteDB-Samples/hasura-ecommerce/blob/master/RUN_LOCAL.md
[voyager-export-dir.zip](https://github.com/yugabyte/yb-voyager/files/10581175/voyager-export-dir.zip)

**Comment by priyanshi-yb** [comment]
This issue is not related to Voyager, it is because of incompatibility between Postgres and YugabyteDB.
