### ISSUE TITLE
Export data aborts in case of all the columns are BLOBs in a table

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#77]
The below error comes:
```
FATAL: no column to export for table blob_dts, aborting
```

Observed with MySQL, but should be true for Oracle also

**Comment by rahulb-yb** [comment]
Fix found: ora2pg fails to write to the err/stdout buffers before we check for it, the code then fails to catch the error that ora2pg reports- need continuous monitoring of these buffers in our code

**Comment by kneeraj** [comment]
Very unusual case. Closing.
