### ISSUE TITLE
docker install yb-voyager host script doesn't have sudo if root needed for docker

### ISSUE THREAD

**Issue by markwjeske** [yugabyte/yb-voyager#823]
Jira Link: [DB-13454](https://yugabyte.atlassian.net/browse/DB-13454)
After installing voyager for docker and installing the host script yb-voyager I get the following:

yb-voyager version
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.

The last line of /usr/local/bin/yb-voyager has:

$dockerCMD

Adding sudo allows the script to run:

sudo $dockerCMD

yb-voyager version
GIT_COMMIT_HASH=af2176a3b9d346bb23c51fdfc508bc863cf992c1
VERSION=1.2.0

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore.
