### ISSUE TITLE
How to create a spatial index on a POSTGIS GEOMETRY field?

### ISSUE THREAD

**Issue by julor** [yugabyte/yb-voyager#835]
Jira Link: [DB-13468](https://yugabyte.atlassian.net/browse/DB-13468)
1.create index on poly using gist (geom)？ 
>ERROR:  index method "gist" not supported yet!

2.create index on poly using ybgin (geom)?
> ERROR:  data type geometry has no default operator class for access method "ybgin"
HINT:  You must specify an operator class for the index or define a default operator class for the data type.

**Comment by hbhanawat** [comment]
Is this a DB issue? Please open it in a yugabytedb repo.
