### ISSUE TITLE
[import data file] Utilizing import data file for large multi-GB data files leaves large number of 0 byte files and large inode after exit

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yb-voyager#900]
Jira Link: [DB-13464](https://yugabyte.atlassian.net/browse/DB-13464)
When utilizing the import data file option, voyager carves up the input data file into small 20000 record chunks by default in the metadata directory. When yb-voyager finishes processing each file, it leaves a zero length file in place. Over a large file set this can create a very large directory with thousands of these files. It would be nice if voyager removed these files on successful exit if they are no longer needed.

**Comment by hbhanawat** [comment]
Older issue. Not relevant anymore. Please reopen if seen again.
