### ISSUE TITLE
Upgrade pg_dump to version 15

### ISSUE THREAD

**Issue by pablopla** [yugabyte/yb-voyager#986]
Jira Link: [DB-13462](https://yugabyte.atlassian.net/browse/DB-13462)
When trying to use voyager in docker to import a database from PostgreSQL 15 I'm getting an error:
```pg_dump: error: aborting because of server version mismatch```
```pg_dump --version``` in the voygaer container shows:
```pg_dump (PostgreSQL) 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)```
Since the workflow requires running analyze-schema to find incompatibilities anyway there shouldn't be a reason not support the latest PostgreSQL release.

I was able to install postgresql-15 in the container with steps from the [installer script](https://github.com/yugabyte/yb-voyager/blob/main/installer_scripts/install-yb-voyager#L555) and the migration worked.

```Dockerfile
FROM golang:latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM amd64/ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
RUN apt-get update && \
    apt-get install -y lsb-release gnupg2 wget && \
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget -nv -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql
RUN apt-get update && \
    apt-get install -y wget curl openjdk-17-jre && \
    wget https://s3.us-west-2.amazonaws.com/downloads.yugabyte.com/repos/reporpms/yb-apt-repo_1.0.0_all.deb && \
    apt-get install -y ./yb-apt-repo_1.0.0_all.deb && \
    apt-get update && \
    apt-get upgrade -y binutils && \
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash && \
    mkdir -p /opt/yb-voyager && \
    apt-get install -y yb-voyager && \
    rm -rf /yb-apt-repo_1.0.0_all.deb && \
    apt-get clean
COPY --from=0 $HOME/go/bin/dlv /usr/local/bin
CMD [“yb-voyager”]
```

**Comment by hbhanawat** [comment]
Already done. Marking it as closed.
